### ISSUE TITLE
pm2 start by cluster mode will throw error listen EADDRINUSE

### ISSUE THREAD

**Issue by WynnLin** [Unitech/pm2#4022] opened 2018-11-13 08:13 UTC
## What's going wrong?
When i startde my node with pm2 by cluster mode, it will give the error **EADDRINUSE**

## How could we reproduce this issue?
Here is my code:
1. node code
![image](https://user-images.githubusercontent.com/26760434/48399200-f6007500-e75d-11e8-9cce-b6a295a5502b.png)
2. pm2 start json
![image](https://user-images.githubusercontent.com/26760434/48399211-044e9100-e75e-11e8-8343-878b19ef55d3.png)
3. package.json
![image](https://user-images.githubusercontent.com/26760434/48399243-19c3bb00-e75e-11e8-8d28-e2040e62c3dd.png)

## Supporting information
Here is the error
![image](https://user-images.githubusercontent.com/26760434/48399278-2e07b800-e75e-11e8-90a1-a8066814ecbe.png)

```
$ pm2 report
```
pm2 version: 3.2.2
node version: v10.7.0
npm version: 6.1.0
both error in MacOx and ubuntu
![image](https://user-images.githubusercontent.com/26760434/48399308-411a8800-e75e-11e8-93d6-ecbc792a0512.png)
![image](https://user-images.githubusercontent.com/26760434/48399315-47a8ff80-e75e-11e8-8167-b650f84b6cfc.png)

I have tried the change exec_mode with **cluster_mode** and **cluster**. None of them works for me!
So, Please Help Me

**Comment by WynnLin** [comment] 2018-11-14 02:44
I tried to delete the exec_mode option, but keep instances option. The app will start by cluster mode without the **EADDRINUSE** error.
It seems to delete the exec_mode option is a way to solve the problem.
But why ?

**Comment by SaKKo** [comment] 2018-11-14 08:51
same for me too, i've been trying to change exec mode and it doesn't work.
it only work if i delete `exec_mode` from ecosystem.json

**Comment by Unitech** [comment] 2018-12-03 15:39
duplicate of https://github.com/Unitech/pm2/issues/3987

**Closed by Unitech** 2018-12-03 15:39 UTC
