### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by babnik63** [Unitech/PM2#584] opened 2014-07-21 12:26 UTC
I think that pm2 does not support windows.
Is it correct? Is there any plan for supporting windows?

**Comment by bdadam** [comment] 2015-01-02 20:13
At first glance the Windows support seems to be fine now, except that a command window (cmd.exe) keeps popping up constantly while at least one process is running or at the time when a process is being restarted by watch. The window disappears within a second or less, but it's still a little annoying for the user.
Sorry, I can't pursue this issue now, but maybe someone has a clue why it's happening.

**Comment by HalfdanJ** [comment] 2015-01-21 01:03
I keep getting the same problem as #6, where the deamon launches without problems (and i'm able to monitor it on keymetrics.io), but apps don't start. there are no errors. the table of apps is just empty. 
Any ideas where to look?

**Comment by echiu64** [comment] 2015-01-31 21:14
Try my branch or take this pull: https://github.com/Unitech/PM2/pull/982
https://github.com/echiu64/PM2/tree/development

Looking for more testing.. seems to work fine for my local dev work

**Comment by HalfdanJ** [comment] 2015-02-01 12:57
This solves the problem with launching nodes, but `pm2 logs` doesn't work. 

```
$ pm2 logs
######## Starting streaming logs for [all] process
events.js:72 

Error: spawn ENOENT
```

**Comment by echiu64** [comment] 2015-02-02 02:42
Can you delete your pm2 home directory? On windows 7/vista it should be c:\users\<username>\.pm2

Also, try running with DEBUG=* in your environment variables and send me the output

**Comment by echiu64** [comment] 2015-02-02 04:27
There remains some RPC issues connecting to the rpc.sock pipe... tracking it down when I can...

**Comment by echiu64** [comment] 2015-02-02 05:06
Not RPC issues, but killing Satan issues. Pull https://github.com/Unitech/PM2/pull/986 created since windows doesn't support SIGQUIT.

HalfdanJ, try my windoze branch https://github.com/echiu64/PM2/tree/windoze, it has some additional logging when running with DEBUG=* in your environment variable. Be sure to restart pm2 daemons (and kill them manually and pm2 kill doesn't work w/o my latest patches)

**Comment by HalfdanJ** [comment] 2015-02-02 08:14
@echiu64 running your branch gives me the following error

```
$ pm2 logs

.....
In memory PM2 version: 0.12.4
Local PM2 version: 0.12.3

PM2: Log file "C:\Users\halfdanj\.pm2\pm2.log" does not exists.
```

And then the error code as previous. And when i look up that path i get the same result, no pm2.log file. But there is a `logs/app-error-0` and  `logs/app-out-0` file

**Comment by HalfdanJ** [comment] 2015-02-02 08:24
@echiu64 I still get the error running `PM2 logs`

  pm2:constants Windows detected +0ms
  pm2:satan [PING PM2] Trying to connect to server +80ms
  axon:sock connect attempt null://./pipe/rpc.sock +0ms
  axon:sock connect +3ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +1ms
  axon:sock closing +0ms
  axon:sock closing 1 connections +0ms
  pm2:satan Daemon alive +7ms
  axon:sock remove socket 0 +1ms
  pm2:satan Launching RPC client on port \\.\pipe\rpc.sock undefined +1ms
  axon:sock connect attempt null://./pipe/rpc.sock +1ms
  axon:sock connect +0ms
  axon:sock add socket 0 +1ms
  axon:queue flush 0 messages +0ms
  pm2:satan Connected to Daemon +1ms
  pm2:cli Got message from Satan as succesfully connected to PM2, now parsing ar
guments +9ms
  pm2:satan Calling daemon method pm2:getVersion +0ms
  pm2:satan Calling daemon method pm2:getMonitorData +3ms
########### Starting streaming logs for [all] process

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by echiu64** [comment] 2015-02-02 15:25
Can you run using my latest branch? You should see more info like:
```
pm2:constants PM2_ROOT_PATH: C:\Users\echiu\.pm2 +0ms
```

Also, just do a pm2 info and then pm2 logs as a test case. If that works, do a "node pm2 start test\fixtures\echo.js" and then "pm2 logs" 

Would be good to see the output of whatever process you spawn.

**Comment by HalfdanJ** [comment] 2015-02-02 15:31
Hmm i am running your branch, but I dont see the `pm2:constants PM2_ROOT_PATH`.

**Comment by HalfdanJ** [comment] 2015-02-02 15:33
Sorry, had not checked out the correct branch... But same error still

```
C:\node\app-playground>pm2 logs
  pm2:constants PM2_ROOT_PATH: C:\Users\drexjojo\.pm2 +0ms
  pm2:constants Windows detected +5ms
  pm2:satan [PING PM2] Trying to connect to server +76ms
  axon:sock connect attempt null://./pipe/rpc.sock +0ms
  axon:sock connect +3ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +1ms
  axon:sock closing +1ms
  axon:sock closing 1 connections +1ms
  pm2:satan Daemon alive +8ms
  axon:sock remove socket 0 +3ms
  pm2:satan Launching RPC client on port \\.\pipe\rpc.sock undefined +3ms
  axon:sock connect attempt null://./pipe/rpc.sock +1ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +1ms
  pm2:satan Connected to Daemon +4ms
  pm2:cli Got message from Satan as succesfully connected to PM2, now parsing ar
guments +5ms
  pm2:satan Calling daemon method pm2:getVersion +1ms
  pm2:satan Calling daemon method pm2:getMonitorData +3ms
########### Starting streaming logs for [all] process

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

```

**Comment by echiu64** [comment] 2015-02-02 15:35
Steps to reproduce? Are you spawning something? Try:
1) kill all node processes
2) pm2 list
3) pm2 logs

If that works, then spawn something like test/fixtures/echo.js and then running pm2 logs

**Comment by HalfdanJ** [comment] 2015-02-02 15:38
Yes, that is what i do

Full stack:
```
C:\node\app-playground>pm2 kill
  pm2:constants PM2_ROOT_PATH: C:\Users\drexjojo\.pm2 +0ms
  pm2:constants Windows detected +4ms
  pm2:satan [PING PM2] Trying to connect to server +74ms
  axon:sock connect attempt null://./pipe/rpc.sock +0ms
  axon:sock connect +3ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +1ms
  axon:sock closing +0ms
  axon:sock closing 1 connections +1ms
  pm2:satan Daemon alive +7ms
  axon:sock remove socket 0 +1ms
  pm2:satan Launching RPC client on port \\.\pipe\rpc.sock undefined +1ms
  axon:sock connect attempt null://./pipe/rpc.sock +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  pm2:satan Connected to Daemon +1ms
  pm2:cli Got message from Satan as succesfully connected to PM2, now parsing ar
guments +9ms
  pm2:satan Calling daemon method pm2:getVersion +1ms
[PM2] Stopping PM2...
  pm2:satan Calling daemon method pm2:getMonitorData +4ms
[PM2] [WARN] No process found
[PM2] All processes has been stopped and deleted
  pm2:interface:daemon Killing interactor #1 ping +1ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon
+0ms
  axon:sock connect attempt null://./pipe/interactor.sock +16ms
  axon:sock error ENOENT +0ms
  axon:sock ignored ENOENT +0ms
  axon:sock attempting reconnect +106ms
  axon:sock closing +1ms
  axon:sock closing 0 connections +1ms
  pm2:interface:daemon Interactor Daemon not launched +109ms
  axon:sock connect attempt null://./pipe/interactor.sock +1ms
  pm2:interface:daemon Interactor online +2ms false
  pm2:satan Calling stopWatch +1ms
  pm2:satan Calling daemon method pm2:killMe +0ms
  axon:sock error ENOENT +3ms
  axon:sock ignored ENOENT +1ms
  pm2:satan Stop watching +2ms

C:\node\app-playground>pm2 list
  pm2:constants PM2_ROOT_PATH: C:\Users\drexjojo\.pm2 +0ms
  pm2:constants Windows detected +5ms
  pm2:satan [PING PM2] Trying to connect to server +75ms
  axon:sock connect attempt null://./pipe/rpc.sock +0ms
  axon:sock error ENOENT +2ms
  axon:sock ignored ENOENT +1ms
  axon:sock attempting reconnect +101ms
  axon:sock closing +2ms
  axon:sock closing 0 connections +0ms
  pm2:satan Daemon not launched +110ms
  axon:sock connect attempt null://./pipe/rpc.sock +2ms
[PM2] Spawning PM2 daemon
  pm2:satan Launching daemon +2ms
  pm2:satan env.PM2_HOME: undefined +1ms
  pm2:satan env.HOME: undefined +1ms
  pm2:satan env.HOMEPATH: \Users\drexjojo +0ms
  pm2:satan resolved HOME: \Users\drexjojo +1ms
  axon:sock error ENOENT +12ms
  axon:sock ignored ENOENT +1ms
  pm2:satan PM2 daemon launched +217ms { online: true, success: true, pid: 3256,
 pm2_version: '0.12.4' }
  pm2:interface:daemon Interaction file does not exists +4ms
[PM2] Success
  pm2:satan Launching RPC client on port \\.\pipe\rpc.sock undefined +0ms
  axon:sock connect attempt null://./pipe/rpc.sock +213ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +1ms
  pm2:satan Connected to Daemon +2ms
  pm2:cli Got message from Satan as succesfully connected to PM2, now parsing ar
guments +5ms
  pm2:satan Calling daemon method pm2:getVersion +1ms
  pm2:satan Calling daemon method pm2:getMonitorData +4ms
  pm2:monit Getting interaction info +2ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon
+1ms
  axon:sock connect attempt null://./pipe/interactor.sock +13ms
  axon:sock error ENOENT +1ms
  axon:sock ignored ENOENT +0ms
  axon:sock attempting reconnect +100ms
  axon:sock closing +1ms
  axon:sock closing 0 connections +1ms
  pm2:interface:daemon Interactor Daemon not launched +104ms
  axon:sock connect attempt null://./pipe/interactor.sock +1ms
  pm2:satan Calling daemon method pm2:getMonitorData +2ms
  axon:sock error ENOENT +2ms
  axon:sock ignored ENOENT +1ms
┌──────────┬────┬──────┬─────┬────────┬───────────┬────────┬────────┬──────────┐

│ App name │ id │ mode │ PID │ status │ restarted │ uptime │ memory │ watching │

└──────────┴────┴──────┴─────┴────────┴───────────┴────────┴────────┴──────────┘

 Use `pm2 info <id|name>` to get more details about an app
  pm2:satan Disconnecting PM2 RPC +10ms
  axon:sock closing +10ms
  axon:sock closing 1 connections +0ms
  axon:sock remove socket 0 +1ms
  pm2:satan PM2 RPC cleanly closed +3ms

C:\node\app-playground>pm2 logs
  pm2:constants PM2_ROOT_PATH: C:\Users\drexjojo\.pm2 +0ms
  pm2:constants Windows detected +5ms
  pm2:satan [PING PM2] Trying to connect to server +77ms
  axon:sock connect attempt null://./pipe/rpc.sock +0ms
  axon:sock connect +3ms
  axon:sock add socket 0 +1ms
  axon:queue flush 0 messages +0ms
  axon:sock closing +1ms
  axon:sock closing 1 connections +1ms
  pm2:satan Daemon alive +8ms
  axon:sock remove socket 0 +0ms
  pm2:satan Launching RPC client on port \\.\pipe\rpc.sock undefined +1ms
  axon:sock connect attempt null://./pipe/rpc.sock +1ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  pm2:satan Connected to Daemon +2ms
  pm2:cli Got message from Satan as succesfully connected to PM2, now parsing ar
guments +8ms
  pm2:satan Calling daemon method pm2:getVersion +0ms
  pm2:satan Calling daemon method pm2:getMonitorData +4ms
########### Starting streaming logs for [all] process

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by echiu64** [comment] 2015-02-02 15:50
Weird... added more debugging for you in this branch:
https://github.com/echiu64/PM2/tree/halfdanj

You should see:
```
  pm2:monit fallbackLogStream list len: 0 +11ms
```
When you run "pm2 logs"

If that still fails, as I can't reproduce, you'll have to track down the source of the ENOENT. You can use process monitor (https://technet.microsoft.com/en-us/sysinternals/bb896645)

I'm running Win7x64, what's your environment?

**Comment by HalfdanJ** [comment] 2015-02-02 16:26
That line is visible

I've tried to follow th ENOENT, and i have found out why its bugging. I dont have tail.exe installed. (its looking for it in `%appdata%\npm\tail.exe` I tried to install it with `npm install tail -g`, but this does not create a tail.exe file. Any clues why i dont have it? (i've reproduced this on several windows machines) 

My OS is windows 7x64

**Comment by echiu64** [comment] 2015-02-02 16:56
I don't think tail npm installs tail.exe. Try installing git, that's where mine comes from. I have several flavours of tail on my machine tbh.... it's probably searching the whole path for tail....

**Comment by echiu64** [comment] 2015-02-02 17:00
I'll also see if i can sub in the tail NPM over spawning a tail process...

**Comment by echiu64** [comment] 2015-02-02 17:19
None of the tail implementations on npm really fit, so I'll pass on this for now...
In the meantime, pull https://github.com/Unitech/PM2/pull/988 opened to note the tail.exe dependency on windows

**Comment by HalfdanJ** [comment] 2015-02-03 10:17
I got git installed on this windows machine, it did not install any tail command
I've installed tail with Windows Resource Kit (http://www.microsoft.com/downloads/en/confirmation.aspx?familyId=9d467a69-57ff-4ae7-96ee-b18c4790cffd&displayLang=en) 
But there is still problems, the windows tail command expects the command like this: 
```
tail -10 C:\Users\drexjojo\.pm2\logs\app-out-0.log
```

but the implementation is like this:

```
  var tail = spawn('tail', ['-f', '-n', lines, path])
```

**Comment by echiu64** [comment] 2015-02-03 14:17
Get a GNU compatible version of tail... https://msysgit.github.io/ comes with a bunch of gnu utils bundled in, try that.

**Comment by HalfdanJ** [comment] 2015-02-03 14:21
Thanks that works. Should be added to a readme.

**Comment by echiu64** [comment] 2015-02-03 14:31
Done, updated in my pull request

**Comment by soyuka** [comment] 2015-02-03 14:51
:+1: nice work @echiu64 thanks!

**Comment by echiu64** [comment] 2015-02-03 19:21
Tracked down the console window opening and closing all the time. Looks like it's the call to pidusage.stat in getMonitorData. This runs exec() on wmic to grab the process information to get memory stats. There's no easy way to get process memory usage without calling some process that will cause a console window to temporarily appear. If anyone has any suggestions, I'd be willing to try them out.

Already tried using a "ps" port and tasklist to no avail. Switching to spawn() on wmic doesn't help either.

**Comment by echiu64** [comment] 2015-02-03 19:25
Actually switching to spawn may work... stay tuned.

**Comment by soyuka** [comment] 2015-02-03 19:41
@echiu64 There were a few tries with different windows tools to get monitor data without wmic (https://github.com/soyuka/pidusage/pulls?q=is%3Apr+is%3Aclosed) but none was better then using wmic*. 

Sadly I have no windows computer to test this, I can't remember that windows was opening a `cmd.exe` while trying on my virtual machine.

*A better way would be using `typeperf -sc 1 "\\COMPUTER-NAME\Process(node)\% Processor Time" "\\COMPUTER-NAME\Process(node)\Working Set"` but it has locales issues and won't be the same command on a French computer for example. Thanks microsoft...

**Comment by echiu64** [comment] 2015-02-03 19:44
Changing pidusage dependency to my pidusage branch should eliminate the window popping when doing things like "pm2 list", as well as the periodic monitor data collection (every 30s?)

```javascript
"pidusage"            : "git+https://github.com/echiu64/pidusage.git#spawn"
```
I'll open a pull to see if the maintainer will take it...

**Comment by Unitech** [comment] 2015-02-09 20:10
All PR has been merged and published to PM2 0.12.5

@windows users
Should we put a pm2.cmd as npm and apm do?

https://github.com/atom/apm/blob/master/bin/apm.cmd
https://github.com/npm/npm/blob/master/bin/npm.cmd

This also?
https://github.com/npm/npm/blob/master/make.bat

**Comment by echiu64** [comment] 2015-02-09 20:43
npm looks good, apm.. no comment.

**Comment by echiu64** [comment] 2015-02-24 13:59
Anything outstanding or can this issue be closed now? I haven't encountered any more open issues at this time.

**Closed** 2015-02-24 14:18 UTC
Labels: 1.0, enhancement, need doc, need pr, portability
