### ISSUE TITLE
pm2 memory leak

### ISSUE THREAD

**Issue by songky08** [Unitech/pm2#4134] opened 2019-01-23 06:34 UTC
## What's going wrong?
Memory of server is slowly increasing and I got out of memory.
I’ve been debugging my server in chrome, the memory periodically keeps objects that seems to histogram every 0.5 ~ 1 second. According to this [document](http://pm2.keymetrics.io/docs/usage/process-metrics/#histogram), it is supposed to keep datas only last 5 minutes by default, but continuous keep holding objects and slowly increase the memory. I’ve tried turn this metric off, it is default function in pm2 I guess. Pm2 needs extra function to turn metrics off or control period

## How could we reproduce this issue?
Just run server with pm2 and debugging with chrome devtool

## Supporting information
![pm2_memory_leak_issue](https://user-images.githubusercontent.com/12230742/51587213-67f5f700-1f23-11e9-9199-de779966f166.png)

```
--- Daemon -------------------------------------------------
pm2d version         : 3.2.9
node version         : 10.15.0
node path            : not found
argv                 : /usr/local/bin/node,/usr/local/bin/pm2-runtime,start,echosystem.config.js,--env,production
argv0                : node
user                 : user
uid                  : 1001
gid                  : 1001
uptime               : 958min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.9
node version         : 10.15.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : user
uid                  : 1001
gid                  : 1001
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
cpus nb              : 2
freemem              : 68087808
totalmem             : 1004294144
home                 : /home/user
===============================================================================
```

**Comment by shimiml4** [comment] 2019-06-02 07:59
Hi, 
We have reproduce it too, all our micro services have memory leak too since 3.5.1.
Moreover, there is no package.lock file on this repo so we cannot go back to 3.5.0 to as a working version.
We managed to compare 3.5.1 & 3.5.0 and we can see the memory leak is not coming from the pm2 repo code but from 3rd party code.
This is the diff in dependencies:

![image](https://user-images.githubusercontent.com/14826104/58758551-6ff32280-8525-11e9-9fb8-f237b9fcca29.png)

**Comment by shimiml4** [comment] 2019-06-02 10:43
looks like there was a problem with pm2/io@4.2.1 which fixed on 4.2.2 
see https://github.com/keymetrics/pm2-io-apm/issues/252
we verified it on prod and looks like problem solved!

**Comment by Unitech** [comment] 2019-06-03 09:00
Great! Closing now

**Closed by Unitech** 2019-06-03 09:00 UTC

**Comment by shimiml4** [comment] 2019-06-03 09:33
> Great! Closing now

I think you must have package.lock file in order to prevent this kind of issues in the future.

Thanks

**Comment by eminoda** [comment] 2019-09-06 05:40
@shimiml4 I also got memory leak when use PM2 in 3.5.1，now I downgrade to 3.4.1 which is fine in these days.

**Comment by eusonlito** [comment] 2019-09-11 16:43
Same here using version `3.5.1`.

With `node` memory is restored after a image resize process, with `pm2` the memory usage still to max after the request finished.

I'm using node `10.16.3` and process to resize images is using https://github.com/lovell/sharp

```js
'use strict';

const sharp = require('sharp');

module.exports = class extends require('./interface') {
    static image(source, target, config) {
        return sharp(source)
            .resize(config.width, config.height, config.options)
            .jpeg(config.quality)
            .toFile(target);
    }
}
```

`source` is a file route string. The memory increase on every file processed and never is released.

After 2.000 images processed, memory is 3.8G.

```
$ pm2 list
┌─────────────────────────────┬────┬─────────┬──────┬────────┬────────┬─────────┬────────┬──────┬────────────┬──────────┬──────────┐
│ App name                    │ id │ version │ mode │ pid    │ status │ restart │ uptime │ cpu  │ mem        │ user     │ watching │
├─────────────────────────────┼────┼─────────┼──────┼────────┼────────┼─────────┼────────┼──────┼────────────┼──────────┼──────────┤
│ XXXXXXXXXXXXXXXXXXXXXXXXXX  │ 13 │ 0.0.1   │ fork │ 68707  │ online │ 2       │ 31m    │ 0.3% │ 3.8 GB     │ www-data │ disabled │
└─────────────────────────────┴────┴─────────┴──────┴────────┴────────┴─────────┴────────┴──────┴────────────┴──────────┴──────────┘
```

```
$ pm2 env 13
version: 0.0.1
log_date_format: YYYY-MM-DD HH:mm:ss
km_link: false
vizion_running: false
NODE_APP_INSTANCE: 0
PM2_USAGE: CLI
OLDPWD: /var/www/deploy
_: /usr/bin/pm2
LC_NAME: es_ES.UTF-8
HISTTIMEFORMAT: %F %T 
LESSCLOSE: /usr/bin/lesspipe %s %s
LC_TIME: es_ES.UTF-8
XDG_RUNTIME_DIR: /run/user/0
PROMPT_COMMAND:
LESSOPEN: | /usr/bin/lesspipe %s
LC_CTYPE: en_US.UTF-8
LOGNAME: www-data
SHLVL: 2
HOME: /var/www
HISTCONTROL: ignoredups:ignorespace
LC_MEASUREMENT: es_ES.UTF-8
LANG: en_US.UTF-8
PWD: /var/www/deploy
LC_IDENTIFICATION: es_ES.UTF-8
MAIL: /var/mail/www-data
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LC_TELEPHONE: es_ES.UTF-8
HISTFILESIZE: -1
USER: www-data
LC_ALL: en_US.UTF-8
LC_NUMERIC: es_ES.UTF-8
HISTSIZE: -1
TERM: xterm-256color
SHELL: /bin/bash
LC_MONETARY: es_ES.UTF-8
XDG_SESSION_ID: 2783
LC_ADDRESS: es_ES.UTF-8
LC_PAPER: es_ES.UTF-8
PM2_HOME: /var/www/.pm2
unique_id: 3ff429e9-a9e7-480e-b26c-aa3461aec964
node_version: 10.16.3
```

I need to restart on every image resize batch process.

**Comment by eusonlito** [comment] 2019-09-11 16:53
As @eminoda say, downgrading to 3.4.1 solves the problem.

**Comment by himadrinath** [comment] 2019-10-06 09:27
no its not solve the problem.

**Comment by prinze77** [comment] 2020-05-23 22:41
Any updates ?

**Comment by hakimelek** [comment] 2020-10-22 13:22
Is this still an issue for anyone on v `3.5.1`?

**Comment by Shogobg** [comment] 2021-01-10 04:44
Still having this issue with 4.5.1

**Comment by Albo1125** [comment] 2021-01-30 17:10
Still having this issue with 4.5.2.

**Comment by TheAndroidGuy** [comment] 2022-01-31 21:28
I have this issue with 5.1.0

**Comment by qiulang** [comment] 2022-05-13 07:13
I have this issue with 5.2, please refer to https://github.com/Unitech/pm2/issues/5145

**Comment by TheAndroidGuy** [comment] 2022-05-13 10:30
**Update**: I fixed the memory problem by using `jemalloc` as memory allocator. [Here ](https://stackoverflow.com/questions/53234410/how-to-use-node-js-with-jemalloc)are instructions how to change it.

**Comment by qiulang** [comment] 2022-05-15 12:12
@TheAndroidGuy  I have 2 servers running, one with pm2 takes a huge amount of memory, the other just runs normally. I really don't think I can make that judgement.

**Comment by OmgImAlexis** [comment] 2022-05-15 22:02
@qiulang you can still use jemalloc and as the issue you linked to states it's useful for some work loads. All depends on your use case.

**Comment by abdelshok** [comment] 2023-08-29 03:49
It seems that PM2 has been rumored to leak memory for about 9 years now @OmgImAlexis.

**Comment by ianharrigan** [comment] 2024-03-01 08:38
how would we set "pmx: false" via the js api?
