### ISSUE TITLE
Port is in use

### ISSUE THREAD

**Issue by archasek** [Unitech/pm2#2427] opened 2016-10-05 16:37 UTC
#### Expected behaviour

No error
#### Actual behaviour

Very often I get an error that my app port is in use. After 16 restarts, the app has status `errored`.
#### Steps to reproduce

I run my app using `pm2 start processes.json --only firstApp --watch`

`processes.json`:

```
{
    "apps": [
        {
            "name": "firstApp",
            "script": "bin/www",
            "watch": "/",
            "ignore_watch": ["frontend/", ".*"],
            "log_date_format" : "YYYY-MM-DD HH:mm",
            "env": {
                "NODE_ENV": "development"
            }
        },
        {
            "name": "secondApp",
            "script": "bin/www",
            "env": {
                "NODE_ENV": "production"
            }
        }
    ]
}
```

And of course `bin/www` function that handles error:

```
/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}
```
#### Software versions used

```
OS         : Windows 7 Pro
node.js    : 4.4.5
PM2        : 2.0.18
```
#### PM2 Log output

```
Error: bind EADDRINUSE null:4000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at cb (net.js:1299:16)
    at shared (cluster.js:601:5)
    at Worker.<anonymous> (cluster.js:575:9)
    at process.<anonymous> (cluster.js:736:8)
    at emitTwo (events.js:92:20)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:695:10)
    at internal/child_process.js:497:7
2016-10-05 18:04: Port 4000 is already in use
```

Anything wrong with my configuration?

**Comment by vmarchaud** [comment] 2016-10-05 19:43
Are you sure that another app isnt already listening on port 4000 ?
That's the normal behavior for pm2 to restart your application when its crash and put it in state `errored` when having too much instable restart.

**Comment by cupliz** [comment] 2016-10-05 23:36
i think it's bug in pm2 for windows in how pm2 produce the process on save file

i have this problem too, and the way to create problem is quite easy:
a. generate express template by running 'express -e hbs test'
b. run `pm2 start bin/www --watch`
c. edit any file and save it twice and you got:
`0|test    | GET /users 304 1.061 ms - -
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use
0|test    | Port 3000 is already in use`

i did not face this problem in linux

**Comment by archasek** [comment] 2016-10-06 10:23
Any idea or I should use something else than pm2, e.g. nodemon?

**Comment by vmarchaud** [comment] 2016-10-06 11:45
I'm the only windows dev @Keymetrics, don't really have time right now to investigate the issue, the temp fix is to not use watch mode under Windows, feel free to do want you want or to investigate and PR us a fix for this too ;)

**Comment by soyuka** [comment] 2016-10-06 12:33
I think it's more an issue with `--only` and `--watch` restarting both scripts. 

For a workaround, use this:

```
{
    "apps": [
        {
            "name": "firstApp",
            "script": "bin/www",
            "ignore_watch": ["frontend/", ".*"],
            "log_date_format" : "YYYY-MM-DD HH:mm"
        },
        "env": {
            "NODE_ENV": "development"
        },
        "env_production": {
           "NODE_ENV": "production"
       }
    ]
}
```

Then start the development version by using:

```
pm2-dev start processes.json
```

In production:

```
pm2 start --env production processes.json
```

**Comment by archasek** [comment] 2016-10-06 12:41
@soyuka this is not a valid json file, can you fix it?

**Comment by soyuka** [comment] 2016-10-06 12:46
Whoops, my bad sorry:

```
{
    "apps": [
        {
            "name": "firstApp",
            "script": "bin/www",
            "ignore_watch": ["frontend/", ".*"],
            "log_date_format" : "YYYY-MM-DD HH:mm",
            "env": {
                "NODE_ENV": "development"
            },
            "env_production": {
              "NODE_ENV": "production"
            }
        }
    ]
}
```

**Comment by archasek** [comment] 2016-10-06 13:13
@soyuka I did what you had told me. After a fresh system reboot and running `pm2-dev start processes.json` I unfortunately get all the time:
```
T-0      | Port 4000 is already in use
firstApp-0      | Example app listening on port 4000!
firstApp-0      | Port 4000 is already in use
[rundev] App firstApp restarted
firstApp-0      | Example app listening on port 4000!
firstApp-0      | Port 4000 is already in use
[rundev] App firstApp restarted
firstApp-0      | Example app listening on port 4000!
firstApp-0      | Port 4000 is already in use
[rundev] App firstApp restarted
```

**Comment by archasek** [comment] 2016-10-06 13:55
Seems to be working. But when I click ctrl+c in my console (cmder) I'm still receiving logs. Is it working in the background? If yes - how to terminate it? Thank you.

**Comment by cupliz** [comment] 2016-10-06 22:35
@soyuka i'm still getting Port x i already in use when using `pm2-dev start processes.json` with your json config.

As you said before, it's `--watch` problem. When it restart after saving file, does it check if previous jobs (save+restart) is done and wait? or just add jobs into stack without checking it.

**Comment by soyuka** [comment] 2016-10-06 22:38
First make sure you do :
pm2 delete all

Before starting the new configuration.

The watch behavior is just telling pm2 to restart the current job, so yeah
it should work seamlessly!

**Comment by vmarchaud** [comment] 2016-10-13 10:35
From #2434 are you sure that you aren't watching file that writen when your application start ?

**Comment by manuelbieh** [comment] 2016-10-23 21:24
I created a simple demo repo to reproduce my problem:
https://github.com/manuelbieh/pm2bug

**Comment by vmarchaud** [comment] 2016-10-23 21:38
Is the issue happening without babel too ?

**Comment by manuelbieh** [comment] 2016-10-23 22:17
Nope. Seems to be a babel issue! Replaced the import with require and started app.js directly without any problems!

**Comment by manuelbieh** [comment] 2016-10-24 11:06
So do you have any ideas how I could possibly solve that problem without dropping the babel register hook? A quick workaround would be fine for now 😉

**Comment by archasek** [comment] 2016-10-24 11:08
I had this issue without Babel

**Comment by Unitech** [comment] 2016-10-26 16:39
Could you please have a try of this:

```bash
$ npm install pm2@next -g
$ pm2 update
```

**Comment by manuelbieh** [comment] 2016-10-26 16:51
Looks like it is working! Or at least I haven't had the EADDRINUSE error after 10+ watch/change/restart cycles. Will do some more intense testing later in the evening :smiley:

**Comment by manuelbieh** [comment] 2016-10-28 15:32
Still happens occasionally 😕 

```
Error: listen EADDRINUSE :::9090
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at EventEmitter.listen (W:\_git\karmaplus\src\web-ui\node_modules\express\lib\application.js:617:24)
    at startServer (W:/_git/karmaplus/src/web-ui/app.js:302:24)
    at Object.run (W:/_git/karmaplus/src/web-ui/app.js:340:9)
    at Object.<anonymous> (W:\_git\karmaplus\src\web-ui\index.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function._load (C:\Users\Manuel\AppData\Roaming\nvm\v6.9.0\node_modules\pm2\node_modules\pmx\lib\transaction.js:62:21)
    at Object.<anonymous> (C:\Users\Manuel\AppData\Roaming\nvm\v6.9.0\node_modules\pm2\lib\ProcessContainerFork.js:52:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by vmarchaud** [comment] 2017-01-12 17:01
Might be the watch trigger restart too fast.
See #2629 we group all issue into one.

**Closed by vmarchaud** 2017-01-12 17:01 UTC
Labels: S: Open for PR, SYS: Windows
