### ISSUE TITLE
I can't install pm2-intercom for Windows

### ISSUE THREAD

**Issue by sakaketsukihana** [Unitech/pm2#3494] opened 2018-02-26 10:48 UTC
I tried install pm2-intercom, but error was detected.

C:\Users\d>pm2 install pm2-intercom
[PM2][Module] Installing module pm2-intercom
[PM2][Module] Calling [NPM] to install pm2-intercom ...
D:\Program Files\nodejs\node_global\node_modules\pm2\lib\API\Modules\Modularizer
.js:188
    process.chdir(process.env.HOME);
            ^

TypeError: Bad argument.
    at D:\Program Files\nodejs\node_global\node_modules\pm2\lib\API\Modules\Modu
larizer.js:188:13
    at D:\Program Files\nodejs\node_global\node_modules\pm2\node_modules\mkdirp\
index.js:48:26
    at FSReqWrap.oncomplete (fs.js:153:5)

Please tell me the solution.

```
$ pm2 report

C:\Users\d>pm2 report
===============================================================================
--- PM2 REPORT (Mon Feb 26 2018 18:27:01 GMT+0800 (中国标准时间)) --------------
-----
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.1
node version         : 8.9.4
node path            : undefined
argv                 : D:\Program Files\nodejs\node.exe,D:\Program Files\nodejs\
node_global\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 486min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.1
node version         : 8.9.4
node path            : undefined
argv                 : D:\Program Files\nodejs\node.exe,D:\Program Files\nodejs\
node_global\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : d
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
cpus nb              : 4
freemem              : 3513696256
totalmem             : 8465825792
home                 : C:\Users\d
===============================================================================
--- PM2 list -----------------------------------------------
┌──────┬──────┬────────┬───┬─────┬──────
──┐
│ Name │ mode │ status │ ↺ │ cpu │ memory │
└──────┴──────┴────────┴───┴─────┴──────
──┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────┬──────┬────────┬───┬─────┬──────
──┐
│ Name │ mode │ status │ ↺ │ cpu │ memory │
└──────┴──────┴────────┴───┴─────┴──────
──┘
 Use `pm2 show <id|name>` to get more details about an app
C:\Users\d\.pm2\pm2.log last 20 lines:
PM2        | [2018-02-26 14:46:02] PM2 log: Starting execution sequence in -clus
ter mode- for app name:testing id:3
PM2        | [2018-02-26 14:46:02] PM2 error: (node:1340) [DEP0007] DeprecationW
arning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-02-26 14:46:02] PM2 log: App name:testing id:3 online
PM2        | [2018-02-26 14:46:02] PM2 error: (node:1340) [DEP0007] DeprecationW
arning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-02-26 14:46:06] PM2 log: Stopping app:testing id:0
PM2        | [2018-02-26 14:46:06] PM2 log: Stopping app:testing id:1
PM2        | [2018-02-26 14:46:06] PM2 log: Stopping app:testing id:2
PM2        | [2018-02-26 14:46:06] PM2 log: Stopping app:testing id:3
PM2        | [2018-02-26 14:46:06] PM2 log: App name:testing id:0 disconnected
PM2        | [2018-02-26 14:46:06] PM2 log: App [testing] with id [0] and pid [6
788], exited with code [1] via signal [SIGINT]
PM2        | [2018-02-26 14:46:06] PM2 log: App name:testing id:1 disconnected
PM2        | [2018-02-26 14:46:06] PM2 log: App [testing] with id [1] and pid [3
564], exited with code [1] via signal [SIGINT]
PM2        | [2018-02-26 14:46:06] PM2 log: App name:testing id:2 disconnected
PM2        | [2018-02-26 14:46:06] PM2 log: App [testing] with id [2] and pid [6
424], exited with code [1] via signal [SIGINT]
PM2        | [2018-02-26 14:46:06] PM2 log: App name:testing id:3 disconnected
PM2        | [2018-02-26 14:46:06] PM2 log: App [testing] with id [3] and pid [9
012], exited with code [1] via signal [SIGINT]
PM2        | [2018-02-26 14:46:06] PM2 log: pid=6788 msg=process killed
PM2        | [2018-02-26 14:46:06] PM2 log: pid=3564 msg=process killed
PM2        | [2018-02-26 14:46:06] PM2 log: pid=6424 msg=process killed
PM2        | [2018-02-26 14:46:06] PM2 log: pid=9012 msg=process killed

```

**Comment by vmarchaud** [comment] 2018-02-26 12:32
Duplicate of https://github.com/Unitech/pm2/issues/3456#ref-issue-298690186

**Closed by vmarchaud** 2018-02-26 12:32 UTC
