### ISSUE TITLE
"Error while getting network statistics Error: not supported"

### ISSUE THREAD

**Issue by philipstratford** [Unitech/pm2#4445] opened 2019-10-11 16:11 UTC
I've spent a couple of hours today trying to deal with this issue. I've been running [raneto](https://github.com/gilbitron/Raneto) under PM2 for a couple of years with no issues but today I updated PM2 and it stopped working. No matter what I tried,  `pm2 ls` showed the process's status as "errored" (I even completely reinstalled Node.js). 

I'm very much a novice when it comes to Node and PM2 so I might be doing something wrong, but it seems to me that there's an issue relating to the [systeminformation](https://github.com/sebhildebrandt/systeminformation) module because, as you can see in the file attached, the error that's repeated over and over is:

````
Error while getting network statistics Error: not supported
    at process.nextTick (F:\nodejs\node_modules\pm2\node_modules\systeminformation\lib\filesystem.js:418:21)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Error when retrieving process list TypeError: Cannot read property 'includes' of undefined
    at infos.processes.cpu_sorted.processes.filter.a (F:\nodejs\node_modules\pm2\lib\Sysinfo\SystemInfo.js:295:32)
    at Array.filter (<anonymous>)
    at psList.then.processes (F:\nodejs\node_modules\pm2\lib\Sysinfo\SystemInfo.js:295:12)
````

I eventually downgraded PM2 to v3.5.1 and it all worked correctly again. I have pasted my system information below, although note that it doesn't all reflect the state of my system when the error was occurring because I have since downgraded PM2.

```
--- PM2 report ----------------------------------------------------------------
Date                 : Fri Oct 11 2019 17:00:57 GMT+0100 (British Summer Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.5.1
node version         : 10.16.3
node path            : not found
argv                 : F:\nodejs\node.exe,F:\nodejs\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 6min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.5.1
node version         : 10.16.3
node path            : not found
argv                 : F:\nodejs\node.exe,F:\nodejs\node_modules\pm2\bin\pm2,report
argv0                : F:\nodejs\\node.exe
user                 : phil2415
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
cpus nb              : 2
freemem              : 12345720832
totalmem             : 17179262976
home                 : C:\Users\phil2415
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────────┬──────
│ App name │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user     │ watch
├──────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────────┼──────
│ raneto   │ 0  │ 0.16.4  │ fork │ 1476 │ online │ 52      │ 0s     │ 0%  │ 33.8 MB   │ phil2415 │ disab
└──────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────────┴──────
===============================================================================
--- Daemon logs --------------------------------------------
c:\etc\.pm2\pm2.log last 20 lines:
PM2        | 2019-10-11T17:00:26: PM2 log: App [raneto:0] starting in -fork mode-
PM2        | 2019-10-11T17:00:26: PM2 log: App [raneto:0] online
PM2        | 2019-10-11T17:00:31: PM2 log: App [raneto:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-10-11T17:00:31: PM2 log: App [raneto:0] starting in -fork mode-
PM2        | 2019-10-11T17:00:31: PM2 log: App [raneto:0] online
PM2        | 2019-10-11T17:00:36: PM2 log: App [raneto:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-10-11T17:00:36: PM2 log: App [raneto:0] starting in -fork mode-
PM2        | 2019-10-11T17:00:36: PM2 log: App [raneto:0] online
PM2        | 2019-10-11T17:00:41: PM2 log: App [raneto:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-10-11T17:00:41: PM2 log: App [raneto:0] starting in -fork mode-
PM2        | 2019-10-11T17:00:41: PM2 log: App [raneto:0] online
PM2        | 2019-10-11T17:00:47: PM2 log: App [raneto:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-10-11T17:00:47: PM2 log: App [raneto:0] starting in -fork mode-
PM2        | 2019-10-11T17:00:47: PM2 log: App [raneto:0] online
PM2        | 2019-10-11T17:00:52: PM2 log: App [raneto:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-10-11T17:00:52: PM2 log: App [raneto:0] starting in -fork mode-
PM2        | 2019-10-11T17:00:52: PM2 log: App [raneto:0] online
PM2        | 2019-10-11T17:00:57: PM2 log: App [raneto:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-10-11T17:00:57: PM2 log: App [raneto:0] starting in -fork mode-
PM2        | 2019-10-11T17:00:57: PM2 log: App [raneto:0] online

```

[pm2.log](https://github.com/Unitech/pm2/files/3718558/pm2.log)

**Comment by Unitech** [comment] 2019-10-12 09:56
Thanks for reporting it will be fixed very soon

**Comment by ghariosk** [comment] 2019-10-12 11:36
Experienced a similar issue with 4.0 on Amazon Linux 2. Every command I did just returned:

```bash
[PM2] Spawning PM2 daemon with pm2_home=/home/MY_USER/.pm2
```

**Comment by Unitech** [comment] 2019-10-12 11:48
Can you paste here the logs of the ~/.pm2/pm2.log please?

**Comment by Unitech** [comment] 2019-10-12 12:45
Just tried on Amazon Linux 2 it works

**Comment by Unitech** [comment] 2019-10-12 13:31
@philipstratford just tried on Windows Server, it's working:
(NB: there are error messages in pm2.log but it could not cause any issue on PM2)
Can you provide me more information to reproduce this issue.
```
C:\Users\Administrator\Downloads\Raneto-0.16.4\Raneto-0.16.4>node example\server.js
^C
C:\Users\Administrator\Downloads\Raneto-0.16.4\Raneto-0.16.4>pm2 start example\server.js
[PM2] Starting C:\Users\Administrator\Downloads\Raneto-0.16.4\Raneto-0.16.4\example\server.js in fork_mode (1 instance)
[PM2] Done.
┌────┬─────────────────────────┬─────────┬─────────┬──────────┬────────┬──────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                    │ version │ mode    │ pid      │ uptime │ ↺    │ status   │ cpu      │ mem      │ user     │ watching │
├────┼─────────────────────────┼─────────┼─────────┼──────────┼────────┼──────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ server                  │ 1.0.0   │ fork    │ 2380     │ 0s     │ 0    │ online   │ 0%       │ 23.6mb   │ Adm… │ disabled │
└────┴─────────────────────────┴─────────┴─────────┴──────────┴────────┴──────┴──────────┴──────────┴──────────┴──────────┴──────────┘
host metrics | cpu: 21.8% | mem: 85.7% | net: 0ms ⇓ 0.001mb/s ⇑ 0.001mb/s | disk: ⇓ 0mb/s ⇑ 0mb/s |

C:\Users\Administrator\Downloads\Raneto-0.16.4\Raneto-0.16.4>pm2 ls
┌────┬─────────────────────────┬─────────┬─────────┬──────────┬────────┬──────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                    │ version │ mode    │ pid      │ uptime │ ↺    │ status   │ cpu      │ mem      │ user     │ watching │
├────┼─────────────────────────┼─────────┼─────────┼──────────┼────────┼──────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ server                  │ 1.0.0   │ fork    │ 2380     │ 2s     │ 0    │ online   │ 27.4%    │ 41.9mb   │ Adm… │ disabled │
└────┴─────────────────────────┴─────────┴─────────┴──────────┴────────┴──────┴──────────┴──────────┴──────────┴──────────┴──────────┘
host metrics | cpu: 32.1% | mem: 85.5% | net: 0ms ⇓ 0.001mb/s ⇑ 0.002mb/s | disk: ⇓ 0mb/s ⇑ 0mb/s |
```

**Comment by ghariosk** [comment] 2019-10-12 14:37
Sooo... it looks like I was running node 6 ... 

Logs are :

```bash
const windows = async () => {
                      ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/Sysinfo/SystemInfo.js:3:16)
/usr/lib/node_modules/pm2/lib/Sysinfo/psList.js:9
const windows = async () => {
                      ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/Sysinfo/SystemInfo.js:3:16)
/usr/lib/node_modules/pm2/lib/Sysinfo/psList.js:9
const windows = async () => {
                      ^
```

Updated node to most recent and its working great now

**Comment by sukbu** [comment] 2019-10-13 14:03
Logs:
```
PS E:\WEB\nodejs-tutorial> pm2 start main.js --watch --no-daemon
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2019-10-13T22:51:01: PM2 log: Launching in no daemon mode
2019-10-13T22:51:01: PM2 log: [PM2] Starting E:\WEB\nodejs-tutorial\main.js in fork_mode (1 instance)
2019-10-13T22:51:01: PM2 log: [Watch] Start watching main
2019-10-13T22:51:01: PM2 log: App [main:0] starting in -fork mode-
2019-10-13T22:51:01: PM2 log: App [main:0] online
2019-10-13T22:51:01: PM2 log: [PM2] Done.
Error while getting network statistics Error: not supported
    at process.nextTick (C:\Users\tjrqj\AppData\Roaming\npm\node_modules\pm2\node_modules\systeminformation\lib\filesystem.js:418:21)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Error when retrieving process list TypeError: Cannot read property 'includes' of undefined
    at infos.processes.cpu_sorted.processes.filter.a (C:\Users\tjrqj\AppData\Roaming\npm\node_modules\pm2\lib\Sysinfo\SystemInfo.js:295:32)
    at Array.filter (<anonymous>)
    at psList.then.processes (C:\Users\tjrqj\AppData\Roaming\npm\node_modules\pm2\lib\Sysinfo\SystemInfo.js:295:12)
2019-10-13T22:51:02: PM2 log: ┌────┬─────────────────────────┬─────────┬─────────┬──────────┬────────┬──────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                    │ version │ mode    │ pid      │ uptime │ ↺    │ status   │ cpu      │ mem      │ user     │ watching │
├────┼─────────────────────────┼─────────┼─────────┼──────────┼────────┼──────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ main                    │ 1.0.0   │ fork    │ 8252     │ 0s     │ 0    │ online   │ 0%       │ 30.9mb   │ sukbu    │ enabled  │
└────┴─────────────────────────┴─────────┴─────────┴──────────┴────────┴──────┴──────────┴──────────┴──────────┴──────────┴──────────┘
2019-10-13T22:51:02: PM2 log: host metrics | cpu: 32.0% | mem: N/A | net: 0ms ⇓ 0mb/s ⇑ 0mb/s | disk: ⇓ 0mb/s ⇑ 0mb/s |
2019-10-13T22:51:02: PM2 log: [--no-daemon] Continue to stream logs
2019-10-13T22:51:02: PM2 log: [--no-daemon] Exit on target PM2 exit pid=3544
Error while getting network statistics Error: not supported
    at process.nextTick (C:\Users\tjrqj\AppData\Roaming\npm\node_modules\pm2\node_modules\systeminformation\lib\filesystem.js:418:21)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error while getting network statistics Error: not supported
    at process.nextTick (C:\Users\tjrqj\AppData\Roaming\npm\node_modules\pm2\node_modules\systeminformation\lib\filesystem.js:418:21)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error while getting network statistics Error: not supported
    at process.nextTick (C:\Users\tjrqj\AppData\Roaming\npm\node_modules\pm2\node_modules\systeminformation\lib\filesystem.js:418:21)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
====
os: windows 10
node.js version: 10.16.3
pm2 version: 4.0.0
====

I installed pm2 with "npm install pm2 -g" in cmd
and I typed this command "pm2 start main.js --watch --no-daemon" in cmd.

Same issue. How do i solve this problem?

I'm node.js beginner, i did refer some video where [https://www.opentutorials.org/course/3332/22110]

**Comment by Unitech** [comment] 2019-10-13 14:29
@sukbu besides displaying these error logs, your application seems to be running as expected. I will hide this debug logs

**Comment by Unitech** [comment] 2019-10-14 10:12
logs switched in debug one 4.0.1

**Closed by Unitech** 2019-10-14 10:12 UTC
