### ISSUE TITLE
Rejecting promise with string causes error

### ISSUE THREAD

**Issue by RodaBVB** [Unitech/pm2#3881] opened 2018-08-27 10:11 UTC
## What's going wrong?
When rejecting promise with string, application run by PM2 produces the error listed below.
Running application without PM2 (e.x. using forever, or standalone nodejs) works fine.
This is happening only on specific version of PM2 (noted in Support paragraph).

> 0|init     | TypeError: Cannot create property '_length' on string 'String'
> 0|init     |     at process.uncaughtListener (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/src/features/notify.js:85:33)
> 0|init     |     at Object.onceWrapper (events.js:318:30)
> 0|init     |     at emitTwo (events.js:125:13)
> 0|init     |     at process.emit (events.js:213:7)
> 0|init     |     at emitPendingUnhandledRejections (internal/process/promises.js:94:22)
> 0|init     |     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
> 0|init     |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
> 0|init     |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

## How could we reproduce this issue?
Test application for reproduction:

```
const express = require('express');
const app = express();

app.get('/', (req, res) => {
	//testWorking()
	testNotWorking()
	res.send('Hello World test app!')
});

var testWorking = () => {
	return new Promise((resolve, reject) => {
		reject({"key": "String"});
	})
};

var testNotWorking = () => {
	return new Promise((resolve, reject) => {
		reject("String");
	})
};

app.listen(3000, () => {
  console.log('Example app listening on port 3000!')
});

```
## Supporting information
The bug is present on
Node 8.70
PM2 3.0.0 +

On PM2 v2.10.4 and v2.9.2 the example works as expected.

**Comment by wallet77** [comment] 2018-08-27 12:13
Hi @RodaBVB 

Ok, root cause is pm2-io-apm, not directly pm2 (neither node version I guess).
The new apm has been shipped with pm2 3+, that's why you see this error only with those versions.

I will check and fix this ASAP.

**Comment by wallet77** [comment] 2018-08-27 15:17
It's fixed in apm.
It will be shipped with the next pm2 release.

**Closed** 2018-09-10 12:17 UTC
Labels: S: Pending Release

**Comment by tsabbay** [comment] 2018-10-25 16:20
Hi @wallet77 wallet77 ,
we see this error on the last ver of npm, can you confirm if it was fixed/released ?
@RodaBVB  was it resolved for you ?
