### ISSUE TITLE
Can't start global (or linked) npm module on Windows 

### ISSUE THREAD

**Issue by hugomallet** [Unitech/pm2#2037] opened 2016-03-22 16:42 UTC
Hello,

Config:
Windows 7 / 10
PM2 1.0.2
Node 4.4.0 / 5.9.0

On Windows,

when starting a linked npm "bin" with:

``` bash
pm2 start <npm module>
```

the following error is thrown:

``` bash
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function._load (node_modules\pm2\node_modules\pmx\lib\transaction.js:62:21)
    at Object.<anonymous> (node_modules\pm2\lib\ProcessContainerFork.js:41:21)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
```

The issue seems to come from the chosen interpreter (node). The file which is executed in node is the generated <npm module>.CMD file.

So we tried to change the script with:

``` bash
pm2 start cmd.exe -- /c <npm module>
```

/c option is not correctly interpreted so we decided to try directly in the pm2 forkMode.js file:

``` js
// ForkMode.js:91
 var cspr = spawn('cmd', ['/c', '<npm module>'], {
          env      : pm2_env,
          detached : true,
          cwd      : pm2_env.pm_cwd || process.cwd(),
          stdio    : ['pipe', 'pipe', 'pipe', 'ipc'] //Same as fork() in node core
        });
```

At this point we got the following error:

``` bash
Error: EBADF: bad file descriptor, uv_pipe_open
    at Error (native)
    at Object.exports._forkChild (child_process.js:61:5)
    at Function.startup.processChannel (node.js:856:10)
    at startup (node.js:45:15)
    at node.js:980:3
 child_process.js:61
  p.open(fd);
```

Removing 'ipc' on fd 3 solves the problem.

Any idea to fix this?

**Comment by vmarchaud** [comment] 2016-07-06 14:34
@hugomallet Can you try on the lastest version of pm2 ? This should be fixed since then : 
```
npm remove pm2 -g
npm cache clean
npm install Unitech/pm2#development -g
pm2 update
pm2 start <module>
```

**Comment by hugomallet** [comment] 2016-07-27 15:57
@vmarchaud i still have the same error (pm2 v2.0.1).

**Comment by vmarchaud** [comment] 2016-07-27 19:28
@hugomallet do you have a sample code to reproduce this ?

**Comment by hugomallet** [comment] 2016-07-28 08:20
yes @vmarchaud, i have create a [gist] (https://gist.github.com/hugomallet/51658b0baba588c215c6a0272781c2cb).

**Comment by vmarchaud** [comment] 2016-07-29 00:26
@hugomallet Will look into this when i can access my windows setup, will keep you up to date with the issue :)

**Comment by yangg** [comment] 2016-08-04 08:41
Same error when I start `gulp watch` on window s(the same on development branch)
```
Error: EBADF: bad file descriptor, uv_pipe_open
    at Error (native)
    at Object.exports._forkChild (child_process.js:61:5)
    at Function.startup.processChannel (node.js:856:10)
    at startup (node.js:45:15)
    at node.js:980:3
 child_process.js:61
  p.open(fd);
```

**Comment by vmarchaud** [comment] 2016-08-04 12:35
@yangg Can you try to start a app script [like this one](http://pastebin.com/w6BPQwzg) ? (dont sure its working, dont have any gulp project to test )

**Comment by yangg** [comment] 2016-08-05 01:53
@vmarchaud `script: "."` seems not work
get the following error
```
[PM2][WARN] Applications undefined not running, starting...
[PM2][ERROR] No script path - aborting
No script path - aborting
```

**Comment by vmarchaud** [comment] 2016-08-05 12:28
@yangg Will try asap

**Comment by musahaidari** [comment] 2016-11-08 10:47
Hello,

Just to mention, I have this issue too, using the programmatic API and stand alone version. http://stackoverflow.com/questions/40481215/failing-to-use-pm2-on-windows

Just in case it helps solving the problem.

**Comment by musahaidari** [comment] 2016-11-08 10:48
Hello,

Just to mention, I have this issue too, using the programmatic API and stand alone version. http://stackoverflow.com/questions/40481215/failing-to-use-pm2-on-windows

Just in case it helps solving the problem.

**Comment by hbrls** [comment] 2016-12-02 00:24
I'm in a docker and the same issue.

**Comment by Kitanotori** [comment] 2017-03-09 05:09
I suddenly got this issue also in Windows 10. Currently running pm2 2.4.2, but same issue with previous versions:

```
Error: EBADF: bad file descriptor, uv_pipe_open
    at Error (native)
    at Object.exports._forkChild (child_process.js:65:5)
    at Object.setupChannel (internal/process.js:239:8)
    at startup (bootstrap_node.js:61:16)
    at bootstrap_node.js:509:3
```

The error goes away if I switch from fork to cluster mode.

**Comment by eisbehr-** [comment] 2017-05-05 08:56
Came across this problem today. Message is a bit different, but it's a npm linked execution too. 😭 

```TEXT
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Object.<anonymous> (C:\Users\*\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:53:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by vmarchaud** [comment] 2017-05-05 09:52
For everyone finding this issue, we don't plan to fix this because we have no idea how to so. 
If anyone find a solution that works and keep the IPC communication we will fix this :)

**Comment by eisbehr-** [comment] 2017-05-05 09:55
Thanks for the info @vmarchaud !
Just to be sure, is there a known work around for this or parameter fixing the problem?

**Comment by vmarchaud** [comment] 2017-05-05 09:59
@eisbehr- Check the content of the issue @hugomallet posted a fix but it remove the IPC communication so some feature doesn't work.

**Closed** 2019-11-18 14:52 UTC
Labels: S: Won't fix, SYS: Daemon, SYS: Windows, T: Bug
