### ISSUE TITLE
--max-memory-restart not working!

### ISSUE THREAD

**Issue by tUrG0n** [Unitech/PM2#1159] opened 2015-04-09 17:12 UTC
I doesn't matter what value I put for  `--max-memory-restart`. Running `pm2 monit` afterward will always show me the same memory buffer of 200MB for every process.

I tried the following commands: `pm2 start watson.coffee --max-memory-restart 600M`
or `pm2 start watson.coffee --max-memory-restart 400M`

And in both cases, here's how `pm2 monit` looks like: 
![screen shot 2015-04-09 at 7 11 53 pm](https://cloud.githubusercontent.com/assets/753950/7072396/51b1ba7c-deec-11e4-86cb-64dcee11f0c2.png)

What am I doing wrong here? 
Thank you :)

**Comment by soyuka** [comment] 2015-04-09 17:13
try 40M ? ^^"

**Comment by jshkurti** [comment] 2015-04-09 17:24
```--max-memory-restart``` will restart your app if it exceeds the memory limit.
Here your app uses only ~50M, therefore is not restarted :)

**Comment by jshkurti** [comment] 2015-04-09 17:25
It doesn't actually have anything to do with ```pm2 monit``` display.

**Comment by tUrG0n** [comment] 2015-04-09 17:31
@jshkurti the problem is that my app is getting restarted as soon as it reaches around 200MB no matter what big value i'm putting :(

I just manually tested it, and i can confirm that behavior :(

@soyuka yes, that will continously cause death of the app. #sad :P

**Comment by jshkurti** [comment] 2015-04-09 17:32
Oh ok, can you show me some ```cat ~/.pm2/pm2.log``` then ? :)

**Comment by tUrG0n** [comment] 2015-04-09 17:33
Yes sir:

```
2015-04-09 13:10:09: Stopping app:watson id:0
2015-04-09 13:10:09: App closed with code: SIGTERM
2015-04-09 13:10:09: App name:watson id:0 exited with code SIGTERM
2015-04-09 13:10:09: [HandleExit] PM2 is being killed, stopping restart procedure...
2015-04-09 13:10:09: Process with pid 26187 killed
2015-04-09 13:10:09: PM2 is being killed via kill method
2015-04-09 13:10:09: RPC socket closed
2015-04-09 13:10:09: PUB socket closed
2015-04-09 13:10:12: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-09 13:10:12: [[[[ PM2/God daemon launched ]]]]
2015-04-09 13:10:12: BUS system [READY] on port /root/.pm2/pub.sock
2015-04-09 13:10:12: RPC interface [READY] on port /root/.pm2/rpc.sock
2015-04-09 13:10:12: Starting execution sequence in -fork mode- for app name:watson id:0
2015-04-09 13:10:12: App name:watson id:0 online
2015-04-09 13:12:45: Stopping app:watson id:0
2015-04-09 13:12:45: App closed with code: SIGTERM
2015-04-09 13:12:45: App name:watson id:0 exited with code SIGTERM
2015-04-09 13:12:45: [HandleExit] PM2 is being killed, stopping restart procedure...
2015-04-09 13:12:45: Process with pid 26225 killed
2015-04-09 13:12:45: PM2 is being killed via kill method
2015-04-09 13:12:45: RPC socket closed
2015-04-09 13:12:45: PUB socket closed
2015-04-09 13:12:48: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-09 13:12:48: [[[[ PM2/God daemon launched ]]]]
2015-04-09 13:12:48: BUS system [READY] on port /root/.pm2/pub.sock
2015-04-09 13:12:48: RPC interface [READY] on port /root/.pm2/rpc.sock
2015-04-09 13:12:48: Starting execution sequence in -fork mode- for app name:watson id:0
2015-04-09 13:12:48: App name:watson id:0 online
2015-04-09 13:12:48: Starting execution sequence in -fork mode- for app name:twitter id:1
2015-04-09 13:12:48: App name:twitter id:1 online
2015-04-09 13:13:43: App closed with code: 1
2015-04-09 13:13:43: App name:twitter id:1 exited with code 1
2015-04-09 13:13:43: Starting execution sequence in -fork mode- for app name:twitter id:1
2015-04-09 13:13:43: App name:twitter id:1 online
2015-04-09 13:30:21: App closed with code: 1
2015-04-09 13:30:21: App name:twitter id:1 exited with code 1
2015-04-09 13:30:21: Starting execution sequence in -fork mode- for app name:twitter id:1
2015-04-09 13:30:21: App name:twitter id:1 online
```

@jshkurti

**Comment by tUrG0n** [comment] 2015-04-09 17:35
![screen shot 2015-04-09 at 7 34 52 pm](https://cloud.githubusercontent.com/assets/753950/7072849/91309846-deef-11e4-8260-51ee40655529.png)
Here's the log of `describe`. 
Shouldn't there be something for `node v8 arguments` ?

**Comment by jshkurti** [comment] 2015-04-09 17:37
Thanks,
--max-memory-restart doesn't seem to be involved here, otherwise it would have shown a message in the logs.
It looks like your app exits by itself.
Have a look at ```/root/.pm2/logs/twitter*.log``` please :)

**Comment by tUrG0n** [comment] 2015-04-09 17:41
oh right silly me. It looks like indeed the app was having problems as the 
`/root/.pm2/logs/twitter*-error.log were not empty.

I'll give it a closer look and tell u if it got fixed.

Question though, running ` pm2 logs` is not extremely intuitive. How can i sort out logs from errors only for a particular app?  (It might also be that tmux is not helping me properly scroll the logs. not sure)

**Comment by jshkurti** [comment] 2015-04-09 17:42
```pm2 logs <id>``` :)

**Comment by tUrG0n** [comment] 2015-04-09 17:48
Ok merci @jshkurti  :)

**Comment by jshkurti** [comment] 2015-04-09 17:50
You're welcome. I'm going to close this now ;)

**Comment by tUrG0n** [comment] 2015-04-09 20:05
@jshkurti Just wanted to inform you that you were right. There was indeed a bug in my code :)

Thank you ^^

**Comment by jaime-ez** [comment] 2015-04-10 15:20
Hi
I'm having this problem. I set max-memory-restart to 95M and processes are not being restarted:
![pm2](https://cloud.githubusercontent.com/assets/4974776/7090795/ecdde612-df7b-11e4-8716-4a0537257228.png)

Any ideas?
Thanks

**Comment by tUrG0n** [comment] 2015-04-10 15:21
What command did you use to set the max memory?

-- 
Piotr Yordanov
``Wake up smarter every day``

http://blog.piotry.me/
https://twitter.com/yordaKhof

On April 10, 2015 at 5:20:52 PM, jaime echegaray zipper (notifications@github.com) wrote:

Hi
I'm having this problem. I set max-memory-restart to 95M and processes are not being restarted:


Any ideas?
Thanks

**Comment by jaime-ez** [comment] 2015-04-10 15:24
I'm doing it programatically:
![pm2-1](https://cloud.githubusercontent.com/assets/4974776/7090907/7c11b322-df7c-11e4-8b65-477326fb263e.png)

**Comment by soyuka** [comment] 2015-04-10 16:05
@jshkurti weird but I got no `max-memory-restart` property in the `pm2_env` on https://github.com/Unitech/PM2/blob/master/lib/Worker.js#L26. 
My test file: https://gist.github.com/soyuka/f71f5479021d3513f1c9

**Comment by jshkurti** [comment] 2015-04-10 16:12
```pm2.start('app.js', { maxMemoryRestart: "10M" }, function(err, proc) {```

**Comment by jshkurti** [comment] 2015-04-10 16:19
@jaime-ez ```scriptArgs``` are the arguments you want to pass to your app, not to PM2 itself.

Actually the way it works when you type : 
```pm2 start app.js --max-memory-restart 50M```
```commander``` module will transform it to ```maxMemoryRestart: "50M"```, then after being processed by PM2 logic it will become an env variable as follows ```max_memory_restart : 52428800 // in bytes this time```.
But since programmatic interface doesn't use commander you have to give it raw-mode : ```maxMemoryRestart```.

**Comment by jshkurti** [comment] 2015-04-10 16:21
@soyuka In your .json declaration you can set it this way  ```"max_memory_restart" : "50M"```

**Comment by jaime-ez** [comment] 2015-04-10 16:44
Worked like a charm. 
I'll say the Advanced Readme could be further updated to clarify this...
Thanks!

**Comment by jshkurti** [comment] 2015-04-10 16:47
I agree :)
Glad I could help.

**Closed by jshkurti** 2015-04-10 16:47 UTC
Labels: inspecting

**Comment by soyuka** [comment] 2015-04-10 16:49
Added this to the readme, thanks @jshkurti!

**Comment by pekeler** [comment] 2015-04-26 06:13
I'm also struggling getting --max-memory-restart to work. What I find suspicious is that pm2 describe doesn't show anything about --max-memory-restart for me. Seems like pm2 is ignoring the argument. What am I doing wrong?
![pm2](https://cloud.githubusercontent.com/assets/42363/7336094/1234240c-eba8-11e4-879e-fb8ce9bf9c7f.png)

**Comment by jshkurti** [comment] 2015-04-26 13:45
PM2 is not ignoring it. The `args` field when you `pm2 desc` only concerns the arguments you want to send to your app, e.g : `pm2 start app.js -- --custom-arg='foo'`.

Your app is only using 7.7MB of RAM which is quite far from 95M.

**Comment by pekeler** [comment] 2015-04-26 15:08
It would be nice if describe or some other pm2 command showed something about --max-memory-restart. Anyways, here's the same (leaky) process, 9 hours later
![pm2-2](https://cloud.githubusercontent.com/assets/42363/7337777/26a71214-ebf3-11e4-93e1-6c22f5d4c85d.png)
And according to describe:
```
status: online
restarts: 1
unstable restarts: 0
uptime: 8h
```

It should have restarted about 3 hours ago (when it was using 95M of ram). A few more hours and I'll have to restart this machine because it'll be out of memory.

**Comment by pekeler** [comment] 2015-05-01 22:36
To follow up: I had to restart my machine a couple more times due to out-of-memory. And then it suddenly started working!? I didn't change any config or software. Without any reason I can think of, pm2 is now restarting my process when it's consuming too much memory. Weird.

Oh, and then I upgraded from iojs 1.4 to 1.8 which seems to have fixed my leak.

**Comment by sequoiar** [comment] 2015-11-01 02:51
run app in cluster mode, what's mean --max-memory-restart ? Does it limit total memory usage for all cluster process, or limit on one process of cluster ?

**Comment by soyuka** [comment] 2015-11-01 10:04
It restarts a process when this one uses more than the allowed memory. Works on 1 cluster process.

**Comment by godspeedelbow** [comment] 2016-03-17 14:29
It's really quite unclear (aka where's the documentation?) how to this if use an `ecosystem.json` file to start the pm2 process. Am I mistaken that this it should be done like this?

```json
    "max_memory_restart" : 52428800,
```

where that value corresponds to 50MB

I didn't get it to work using `"50MB"` as a value.

**Comment by soyuka** [comment] 2016-03-17 16:03
http://pm2.keymetrics.io/docs/usage/process-management/#max-memory-restart ?

**Comment by godspeedelbow** [comment] 2016-03-17 16:11
christ, how did i miss that

**Comment by ChinLeung** [comment] 2016-08-01 13:26
I'm sorry for bumping this issue.

I'm having issues with `max_memory_restart` not working in my json... I'm trying to set the limit of my app to automatically restart when it reaches 1GB memory and here's what I have in my `server.json`:

```
[
    {
        "script": "server.js",
        "name": "Server",
        "max_memory_restart": "1G",
        "watch": true
    }
]
```

I've tried to use `1000M` instead of `1G` and it still goes over the allowed memory. I don't have any screenshot as I just restarted it manually 5 minutes ago but it was running at `1.41GB`.

I think I'm passing the parameter properly because I tried to pass `1GB` and it had an error message saying to input as `K`, `M` or `G`.

Anyone knows what's not working?
Thanks!

**Comment by godspeedelbow** [comment] 2016-08-01 13:31
@ChinLeung did you `pm2 delete` it first? you might have to remove it first and then re-add it before it picks up on that setting

**Comment by ChinLeung** [comment] 2016-08-01 14:18
@godspeedelbow Yes I've tried to `pm2 delete` before changing. But is there any reason why my `"max_memory_restart": "1G"` isn't working?

**Comment by ChinLeung** [comment] 2016-08-02 23:08
After retesting several time, I've finally got it working.

I still don't know why but:

`"max_memory_restart": "1000M"` is working
`"max_memory_restart": "1G"` is **not** working

**Comment by ancmikesmullin** [comment] 2019-06-28 16:52
it would help if `max_memory_restart` could be listed by `pm2 describe` so you know your config is working, especially since the above bug with the "G" notation persists today.

**Comment by pschuster** [comment] 2019-08-11 08:58
I have the same issue: I have built a Docker image with a Node JS server that is started with PM2. Running `ps ax` inside the running container shows me this:

```
PID   USER     TIME  COMMAND
    1 root      2:50 node /usr/local/bin/pm2-runtime --max-memory-restart 800M start dist/server
   18 root     11:59 node /dist/server
   24 root      1:36 PM2 Agent v0.5.26: (/root/.pm2)
```

Therefore, the max memory is set to 800 MB. However, it does not restart. This is what `pm2 list` shows me:

```┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬──────┬────────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu  │ mem        │ user │ watching │
├──────────┼────┼─────────┼──────┼─────┼────────┼─────────┼────────┼──────┼────────────┼──────┼──────────┤
│ server   │ 0  │ N/A     │ fork │ 18  │ online │ 0       │ 10h    │ 2.4% │ 941.7 MB   │ root │ disabled │
└──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴──────┴────────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an App
```

For me, it looks like the setting is just ignored. Any ideas what I might be missing?

**Comment by Abadii** [comment] 2019-09-03 09:09
@pschuster ```pm2-runtime``` requires different parameters. You can check it with ```pm2-runtime -h```. This will generate the following output:

```
Usage: pm2-runtime app.js

  pm2-docker is a drop-in replacement node.js binary with some interesting production features


  Options:

    -V, --version              output the version number
    -i --instances <number>    launch [number] of processes automatically load-balanced. Increase overall performances and performance stability.
    --secret [key]             [MONITORING] keymetrics secret key
    --public [key]             [MONITORING] keymetrics public key
    --machine-name [name]      [MONITORING] keymetrics machine name
    --raw                      raw log output
    --json                     output logs in json format
    --format                   output logs formated like key=val
    --delay <seconds>          delay start of configuration file by <seconds> (default: 0)
    --web [port]               launch process web api on [port] (default to 9615)
    --only <application-name>  only act on one application of configuration
    --no-auto-exit             do not exit if all processes are errored/stopped or 0 apps launched (default: true)
    --env [name]               inject env_[name] env variables in process config file
    --watch                    watch and restart application on file change
    --error <path>             error log file destination (default disabled) (default: /dev/null)
    --output <path>            output log file destination (default disabled) (default: /dev/null)
    -h, --help                 output usage information


  Commands:

    *                       
    start <app.js|json_file>  start an application or json ecosystem file
```

As you can see, the argument ```--max-memory-restart``` is not listed. To get the ```--max-memory-restart``` passed, you could create a ```ecosystem.config.js``` file and pass it to ```pm2-runtime```

After you've configured  ```ecosystem.config.js```, you can start like
```pm2-runtime ecosystem.config.js```

An example of the config file:
```
module.exports = [{
    script: './app.js',
    name: 'test-app',
    args: "-s test -e develop -p 5000",
    exec_mode: 'cluster',
    instances: 'max',
    log_date_format: 'YYYY-MM-DD HH:mm Z',
    max_memory_restart: '1000M',
    cwd: "/var/node",
    watch: false,
    ignore_watch: ["node_modules"],
}]
```

Check out this link: http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/

And this: http://pm2.keymetrics.io/docs/usage/application-declaration/#attributes-available

That should help you out!

**Comment by yanqing6628780** [comment] 2020-01-03 03:41
![WX20200103-112851](https://user-images.githubusercontent.com/8479740/71706010-539dc800-2e1d-11ea-9624-5f51995ddc4d.png)
![WX20200103-112907](https://user-images.githubusercontent.com/8479740/71706008-51d40480-2e1d-11ea-856f-6acbb37e5b46.png)

I have set the `--max-memory-restart` as 400M, but it never restart. The application has been running since Monday of this week.

How should I set the `max-memory-restart` to let it works?

**Comment by sakshi-devotess** [comment] 2026-03-20 12:44
**Title:** PM2 restarting Node.js workers due to high memory usage – need help identifying memory leak / root cause

Hi everyone,

I’m facing an issue where my Node.js application managed by PM2 keeps restarting workers due to exceeding the memory limit.

### 🔍 Problem

PM2 logs show frequent restarts like this:

```
[PM2][WORKER] Process X restarted because it exceeds --max-memory-restart value
(current_memory=2.7GB+ max_memory_limit=~2.3GB)
```

In some cases, memory usage goes up to **3.5GB+** before restart.
script: 'dist/main.js',
instances: 1,
max_memory_restart: '2200M',
exec_mode: 'cluster',
---

### ⚙️ Environment

* Node.js:
* PM2
* OS: Linux (64-bit)
* PM2 mode: Cluster (multiple workers) - 6 instance

---

### 🧠 Observations

* Multiple workers (2–6) are affected
* Memory usage keeps increasing over time
* Restart happens when memory crosses ~2.3GB (`--max-memory-restart`)
* Default Node heap (~2GB) seems exceeded in total RSS, so likely external/buffer memory is also involved

---

### ❓ What I need help with

1. How can I **identify the exact source of memory growth**?
2. Best way to analyze whether this is:

   * a memory leak (heap)
   * buffer/native memory issue
   * or heavy requests causing spikes
3. Recommended tools/workflow to debug in production (heap snapshots, profiling, etc.)

---

### 🧪 What I’ve tried

* Monitoring with `pm2 monit`
* Checking logs with `pm2 logs`
* Planning to use heap snapshots and `process.memoryUsage()`

---

### 🙏 Looking for guidance

If anyone has faced similar issues or can suggest a **step-by-step approach to pinpoint the leak/root cause**, that would be really helpful.

Thanks in advance!
