### ISSUE TITLE
Memory leak on cluster mode for sails js

### ISSUE THREAD

**Issue by shumailarshad** [Unitech/PM2#1453] opened 2015-07-22 08:50 UTC
I have created a new sails js app and did not change any code in it.

Than I used pm2 to launch two instance of that app. Memory keep increasing without hitting app even once.

I have done the same with basic express.js app with following code but it does not increase memory

"
var express = require('express');
var app = express();

app.get('/', function (req, res) {
res.send('Hello World!');
});

var server = app.listen(3000, function () {
var host = server.address().address;
var port = server.address().port;

console.log('Example app listening at http://%s:%s', host, port);
});
"
After around 2 - 3 hrs.. It comes up to:
![screenshot from 2015-07-21 17 59 17](https://cloud.githubusercontent.com/assets/10924934/8821626/25280e54-3057-11e5-9641-ec90fff5689a.png)

After leaving it overnight.. It comes up to:
![screenshot from 2015-07-22 09 11 44](https://cloud.githubusercontent.com/assets/10924934/8821616/0da2a6f4-3057-11e5-96ae-35986961c589.png)

**Comment by soyuka** [comment] 2015-07-22 08:51
How is this related to pm2?

**Comment by shumailarshad** [comment] 2015-07-22 08:52
And when I use fork mode, it did not increase alot and stayed more steady.

![screenshot from 2015-07-22 09 52 36](https://cloud.githubusercontent.com/assets/10924934/8821665/66b859c8-3057-11e5-9385-7e8fd8bea4c4.png)

**Comment by shumailarshad** [comment] 2015-07-22 08:54
I am not sure but it only happens on cluster mode not fork mode (standalone sails app)

**Comment by soyuka** [comment] 2015-07-22 09:03
So? No memory leak with express in cluster mode? Conclusion: it should be related to sails.

**Comment by jshkurti** [comment] 2015-07-27 16:24
Which version of Node.js and Sails exactly ?
I would like to reproduce this bug.
Also a sample code would be nice.

Thanks for reporting this @shumailarshad

**Comment by jshkurti** [comment] 2015-07-28 15:15
Bug confirmed. Inspecting this

**Comment by shumailarshad** [comment] 2015-07-28 15:46
That is not problem. Please do let me know if you need any help in fixing this bug or any other. 

Also, if you need to any more testing on my side, please do let me know.

**Comment by shumailarshad** [comment] 2015-07-28 15:47
So I didn't write single line of code. Just did 
sails new sailsApp
pm2 start app.js -i 2 --name "sailsApp"

**Comment by jshkurti** [comment] 2015-07-28 15:53
Yep thanks. I managed to reproduce it. `sails new projet; cd project; pm2 start app.js -i 2`.
The strange part about it, it's that you don't even have to perform requests with tools like `ab` or `wrk`. It just leaks even without ever hitting http://localhost:1337

**Comment by soyuka** [comment] 2015-07-28 16:11
#3099

**Comment by shumailarshad** [comment] 2015-07-29 09:41
Just to add. As @soyuka mentioned that issue I opened with sails. It seems to behave correctly if we turn off sockets, pubsub in .sailsrc file. But I still don't understand cause of the issue.

**Comment by soyuka** [comment] 2015-07-29 10:23
I've done a few tests with express, sails and a basic http server : 

## Basic http server :
![basic](https://cloud.githubusercontent.com/assets/1321971/8955394/927a58be-35ec-11e5-8ecc-9191d0a7d028.png)
## Express server :
![express](https://cloud.githubusercontent.com/assets/1321971/8955395/927f7592-35ec-11e5-96e5-4342daf8b36e.png)
## Sails server :
![sails](https://cloud.githubusercontent.com/assets/1321971/8955396/928004da-35ec-11e5-8660-15e877dda7e0.png)

Sails seems to be clearly leaking.

**Comment by soyuka** [comment] 2015-07-29 13:47
Closing as a non-pm2 issue

**Comment by jshkurti** [comment] 2015-07-29 13:48
Great work @soyuka :+1:

**Closed by soyuka** 2015-07-29 13:47 UTC
Labels: high-priority, inspecting, leak?
