### ISSUE TITLE
DeprecationWarning: worker.suicide is deprecated

### ISSUE THREAD

**Issue by svipben** [Unitech/pm2#2780] opened 2017-03-19 15:49 UTC
#### Bug
`2017-03-19 17:45:49: (node:4680) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect`

#### Software versions used

```
OS         : Linux Ubuntu 16.04
node.js    : v7.7.3
PM2        : v2.4.2
```

#### PM2 Log output

```
2017-03-19 17:45:49: Starting execution sequence in -cluster mode- for app name:server id:0
2017-03-19 17:45:49: App name:server id:0 online
2017-03-19 17:45:49: Starting execution sequence in -cluster mode- for app name:server id:1
2017-03-19 17:45:49: (node:4680) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
2017-03-19 17:45:49: App name:server id:1 online
2017-03-19 17:45:49: Starting execution sequence in -cluster mode- for app name:server id:2
2017-03-19 17:45:49: (node:4680) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
2017-03-19 17:45:49: App name:server id:2 online
2017-03-19 17:45:49: Starting execution sequence in -cluster mode- for app name:server id:3
2017-03-19 17:45:49: (node:4680) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
2017-03-19 17:45:49: App name:server id:3 online
2017-03-19 17:45:49: (node:4680) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
```

**Comment by vmarchaud** [comment] 2017-03-21 15:33
Are you sure that your daemon is up-to-date ? Try making a `pm2 update` and see if the warning is stil there.

**Comment by svipben** [comment] 2017-03-21 16:58
@vmarchaud PM version 2.4.2, did and still the same warning.

**Comment by sanpoChew** [comment] 2017-03-23 00:19
can confirm, getting the same error with pm2 2.4.2 and node 7.7.2

**Comment by jyotman** [comment] 2017-04-14 13:29
Same here on Ubuntu 16.04! 
pm2 2.4.4
node 7.9.0

**Comment by damianobarbati** [comment] 2017-04-14 22:06
news on this?

**Comment by vmarchaud** [comment] 2017-04-14 22:30
It's a warning, you can ignore it.

**Comment by Unitech** [comment] 2017-04-15 13:54
we never use .suicide in pm2, I don't understand how this warning end up in
logs

**Comment by isaacs** [comment] 2017-06-15 16:54
Is it possible to run your app with the `--trace-deprecation` argument?  Like `node --trace-deprecation my-app.js`  This will show where the deprecated API is being used.

**Comment by vmarchaud** [comment] 2017-06-15 22:52
@isaacs I read the issue over nodejs/node, currently i am maintaining PM2.
But as Unitech, we dropped the use of `worker.suicide` already few months back so we don't really understand from where it can be coming.
I actually run on the issue locally multiple times but ignored it, i'll try with  `--trace-deprecation` tomorrow (don't hesitate to ping me i might forget ^^)

**Comment by isaacs** [comment] 2017-06-20 17:10
@vmarchaud Any update on this?  This is me pinging you because maybe you forgot :)

**Comment by vmarchaud** [comment] 2017-06-20 19:22
Able to reproduce, it's coming from a dependency `fclone`, could you check it out @soyuka  ?
```
2017-06-20 21:20:22: (node:30836) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
    at fclone (/home/vmarchaud/keymetrics/pm2/node_modules/fclone/dist/fclone.js:74:32)
    at Object.clone (/home/vmarchaud/keymetrics/pm2/lib/Utility.js:60:12)
    at /home/vmarchaud/keymetrics/pm2/lib/God/ActionMethods.js:204:32
    at ready (/home/vmarchaud/keymetrics/pm2/lib/God.js:150:15)
    at Worker.<anonymous> (/home/vmarchaud/keymetrics/pm2/lib/God.js:197:18)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:105:13)
    at Worker.emit (events.js:207:7)
    at online (internal/cluster/master.js:249:10)
    at Worker.onmessage (internal/cluster/master.js:236:5)
```

**Comment by vmarchaud** [comment] 2017-06-21 09:50
@isaacs I don't think we can actually avoid accessing `worker.suicide` because we can't just hardcode a key inside `fclone` to ignore it and we need to access it anyway to see if it's a function.
But anyway it should have no impact if removed since we don't use it.

**Comment by soyuka** [comment] 2017-06-21 10:12
I propose we close this as a `wontfix`. We don't use `worker.suicide` and therefore we can safely ignore the warning. This warning only shows up because we access the `suicide` getter, without calling the method.

**Comment by extensionsapp** [comment] 2017-09-11 00:47
Hello.

```

PM2        | App name:hello.com id:1 online
PM2        | (node:14176) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | Change detected on path core for app hello.com - restarting
PM2        | Stopping app:hello.com id:1
PM2        | pid=20058 msg=failed to kill - retrying in 100ms
PM2        | pid=20058 msg=failed to kill - retrying in 100ms
PM2        | pid=20058 msg=failed to kill - retrying in 100ms
PM2        | Process with pid 20058 still alive after 1600ms, sending it SIGKILL now...
PM2        | App name:hello.com id:1 disconnected
PM2        | App [hello.com] with id [1] and pid [20058], exited with code [0] via signal [SIGABRT]
PM2        | pid=20058 msg=process killed
PM2        | Starting execution sequence in -cluster mode- for app name:hello.com id:1
PM2        | App name:hello.com id:1 online
PM2        | (node:14176) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | Change detected on path core for app hello.com - restarting
PM2        | Stopping app:hello.com id:1
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | pid=20083 msg=failed to kill - retrying in 100ms
PM2        | Process with pid 20083 still alive after 1600ms, sending it SIGKILL now...
PM2        | App name:hello.com id:1 disconnected
PM2        | App [hello.com] with id [1] and pid [20083], exited with code [0] via signal [SIGABRT]
PM2        | pid=20083 msg=process killed
PM2        | Starting execution sequence in -cluster mode- for app name:hello.com id:1
PM2        | App name:hello.com id:1 online
PM2        | (node:14176) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
```

**Comment by soyuka** [comment] 2017-09-11 06:04
@extensionsapp the deprecation is not related and is not the one responsible of the app being killed.

**Closed by soyuka** 2017-09-11 06:04 UTC
Labels: S: Need More Data, S: Won't fix

**Comment by feryardiant** [comment] 2018-05-04 16:44
Same issue with v2.10.3

![image](https://user-images.githubusercontent.com/508665/39640394-106f6852-4ff5-11e8-9c61-b49459eeab3c.png)

**Comment by asfo** [comment] 2018-09-10 22:50
Same issue with v3.1.2

**Comment by vmarchaud** [comment] 2018-09-11 08:00
Please ignore it, it's not a problem
