### ISSUE TITLE
Logfile config in environment is not used

### ISSUE THREAD

**Issue by Osterjour** [Unitech/pm2#3195] opened 2017-10-05 13:49 UTC
## What's going wrong?
Configuring separate log files/paths in environments are not used.

## How could we reproduce this issue?
create a process.json like this:
```{
  "apps" : [{
    "name"        : "worker",
    "script"      : "./hello.js",
    "watch"       : false,
    "autorestart" : false,
    "merge_logs"  : true,
    "error_file": "/home/ubuntu/default.log",
    "out_file": "/home/ubuntu/default.log",
    "env": {
      "NODE_ENV": "development",
      "error_file": "/home/ubuntu/dev.log",
      "out_file": "/home/ubuntu/dev.log"
    },
    "env_production" : {
      "NODE_ENV": "production",
      "error_file": "/home/ubuntu/prod.log",
      "out_file": "/home/ubuntu/prod.log"
    }
  }]
}
```
`pm2 start process.json` uses the /home/ubuntu/default.log
`pm2 start process.json --env development` uses the /home/ubuntu/default.log
`pm2 start process.json --env production` uses the /home/ubuntu/default.log
If we don't configure the error_file, out_file or log_file outside of the env_* PM2 always uses the default config (inside of the .pm2/logs/)
The environments itself are working correct (as we made sure via the NODE_ENV), but all log file variables are not used inside of the environments.

## Supporting information
```
===============================================================================
--- PM2 REPORT (Thu Oct 05 2017 13:44:27 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.1
node version         : 8.6.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
uptime               : 5min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.1
node version         : 8.6.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 2
freemem              : 3458596864
totalmem             : 4142297088
home                 : /home/ubuntu
===============================================================================

```

**Comment by vmarchaud** [comment] 2017-10-08 13:03
configuration isn't picked up when inside `env_*` entry, duplicate of https://github.com/Unitech/pm2/issues/3122

**Closed by vmarchaud** 2017-10-08 13:03 UTC
