### ISSUE TITLE
pm2 goes to infinite restart on child.process.exec('pm2 reload other_task')

### ISSUE THREAD

**Issue by fend25** [Unitech/pm2#2133] opened 2016-05-06 09:41 UTC
Hi. Thanks for pm2.

So, there are two tasks started under pm2: task1 and task2.

pm2 goes to infinite restart loop (on task1) when the task1 performs `child_process.exec('pm2 reload task2')`. Task2, by the way, successfully reloads (or restarts, with 'restart' command there is the same result). Although it switches both tasks into watching mode. `--no-autorestart` and `--no-automation` keys don't help.

I created a repo with minimal sample how to reproduce error: https://github.com/fend25/test_pm2_reload

Technical details::
os: ubuntu~14.04.1 x86_64 3.19.0-47-generic
node: v6.0.0
pm2: v1.1.3

Tasks have been started in fork mode, No clusters or so on.

**Comment by Cyral** [comment] 2016-05-06 22:32
+1 I think I am having the same issue, using a pm2 process to restart other processes by running a bash script, process 1 is stopped successfully running "pm2 restart 1" but then the process that executed the script is ran again.

Example: 

spawn("sh", ["update.sh"]);
...
**update.sh:**
echo Updating application
git pull
pm2 restart 1

**Output:**
```
PM2 [Watch] Start watching 1
PM2 Stopping app:<restarted app> 1 id:1
PM2 App [<restarted app>] with id [2] and pid [3425], exited with code [2] via signal [SIGINT]
PM2 Starting execution sequence in -fork mode- for app name:<original app> id:5
PM2 App name:<original app> id:5 online
```

<restarted app> is the app I am trying to restart, but <original app> is started instead of the app that should be restarted.

**Comment by Cyral** [comment] 2016-05-06 22:34
Looks like it might be related to #783

**Comment by Cyral** [comment] 2016-05-07 00:08
Okay so a few things... 

The old fix (that has since been removed) for this issue ([here](https://github.com/Unitech/pm2/pull/782/files)) is incorrect I believe because it restarts the app with a new ID, not the old ID (which breaks restart scripts and such).

Note that the issue also occurs if using the pm2 programmatic API.

I'm really not familiar enough with the pm2 internals to continue trying to fix this, but the issue is that the pm2_id in the environment variable is incorrect because it is using the parents environment variables.

**Comment by Unitech** [comment] 2016-05-18 10:32
Some environment variables are messing with the current process,
A temporary fix:

```javascript
  child_process.exec(`pm2 reload test_pm2_main`, { env : {
    PATH : process.env.PATH,
    HOME : process.env.HOME
  }}, function(err, stderr, stdout) {
    console.log(err, stderr, stdout);
  });
```

Will work on this

**Comment by Unitech** [comment] 2016-05-18 10:43
closing in favor of #2077

**Closed by Unitech** 2016-05-18 10:43 UTC
Labels: bug
