### ISSUE TITLE
EADDRINUSE when restarting in fork mode

### ISSUE THREAD

**Issue by polonel** [Unitech/pm2#2279] opened 2016-07-13 17:34 UTC
I'm having a issue with PM2 not releasing the port used in an ExpressJS app.
Running in Fork mode if I try to restart the app using ``pm2 restart :id`` or ``pm2.restart()``, my app crashes because it detects the EADDRINUSE error and exits. I have also tried to use catch the SIGINT and SIGTERM events to handle the ``server.close() `` but nothing works. If I kill the PM2 process while my app is in an exit loop, it will free the port and I can start the app again.

Note: I am running PM2 embedded in my app with the API. but I have tried the same with the PM2 CLI as well and get same result. 

#### Software versions used

```
OS       : Windows 10
node.js  : 5.0.0
PM2      : 1.1.3
```

**Comment by soyuka** [comment] 2016-07-13 18:24
Can you give some code to reproduce? How did you trigger `pm2.restart`?

You should upgrade node.js 5.0.0 to 6.3.0, or just use LTS `v4.4.7` btw ;)

**Comment by polonel** [comment] 2016-07-13 18:44
I'm starting my app with the following:

    var pm2 = require('pm2');
    var path = require('path');

    pm2.connect(true, function(err) {
       if (err) {
           console.log(err);
           process.exit(2);
       }

       pm2.start({
           name: 'myapp',
           script: 'app.js'
       }, function(err) {
           pm2.disconnect();
           if (err) throw err;
       });

then I simply setup a test route to trigger a restart
```
router.get('/debug/restart', function (req, res) {
            var pm2 = require('pm2');
            pm2.connect(function(err) {
                if (err) throw err;
                pm2.restart('trudesk', function(err) {
                    pm2.disconnect();
                    if (err) throw err;

                    res.send('OK');
                });
            });
        });
```
And it triggers the restart but the app is unable to start listening on my port because its still in use. Here is the code for the ``server.listen``

    server.on('error', function(err) {
                if (err.code === 'EADDRINUSE') {
                    winston.error('Address in use, exiting...');
                    server.close();
                    process.exit();
                } else {
                    winston.error(err.message);
                    throw err;
                }
            });

            server.listen(port, '0.0.0.0', function() {
                winston.info('Now listening on port: ' + port);

                callback();
            });

where port defaults to ``8118``. If I CTRL+C the process in the console (PM2) it release the port and I can star the app again. 

PS: I'm upgrading asap just have a ton of deps that break. :-/

**Comment by vmarchaud** [comment] 2016-08-04 09:49
Trying to reproduce to publish a flix.

**Comment by vmarchaud** [comment] 2016-08-04 10:48
Wasnt able to reproduce with node v0.10.0 and v6.2.2 with `pm2@next` version. If i am not able to reproduce with 5.0.0 i will close the issue, dont hesitate to re-open if you still have this issue.

**Closed** 2016-08-04 10:53 UTC
Labels: Windows
