### ISSUE TITLE
Error using PM2 with node-config when NODE_APP_INSTANCE === 0

### ISSUE THREAD

**Issue by davidhq** [Unitech/pm2#2045] opened 2016-03-27 04:50 UTC
I had big problems using PM2 today with nginx (reverse proxy):

http://serverfault.com/questions/766280/nginx-proxy-pass-cannot-fetch-assets

This seems to be the issue:

https://github.com/lorenwest/node-config/issues/244

and not just warning, I cannot run this app with `pm2` at all... is there a way to make this seamlessly work? Does pm2 need a bugfix or it's just not compatible with `config` package? I tried creating the `default-0.json` with `{}` as described in that thread but it didn't help...

This was a hard one to discover that `pm2` is at fault... `forever` and `passenger` work in this same case...

thank you

**Comment by aarontropy** [comment] 2016-04-16 02:57
I'm having the exact same problem and the `default-0.json` hack didn't work for me either.

The problem is that both PM2 and node-config use the same environment variable, but for very different purposes, and neither provide a namespace.

In the original thread (#1143) that requested the `NODE_APP_INSTANCE` feature, it was suggested that the name of the environment variable should be configurable.  Can we implement that feature?  If the environment variable defaults to `NODE_APP_INSTANCE` it would be a non-breaking change.

**Comment by lahvey** [comment] 2016-06-08 10:57
+1

**Comment by sminogue** [comment] 2016-12-03 12:43
Same issue here... #244 is marked as fixed which I think is crap since it smells like a total hack. This bug is sitting open for like 9 months with no motion... Think I am going to write off PM2 and move on. I'll take a look at forever and passenger thanks :-)

**Comment by vmarchaud** [comment] 2017-06-09 10:08
Published under PM2 2.5 : npm install -g pm2@latest && pm2 update

**Closed by vmarchaud** 2017-06-09 10:08 UTC
Labels: S: Pending Release

**Comment by trongvnau** [comment] 2017-08-07 20:45
Here is what i did to address the issue after reading all of the solutions proposed
1- On your server, make sure you have a "config" folder in your project (/var/www/<your website name>/config) 
2- In config folder, make sure you have the configuration files: default.js, development.js, production.js (or json if you prefer)
3- in config folder, create default-0.js with {} as a content (or default-0.json)
4- Create pm2.config.js like below in your server (put in root folder for example)
NOTE: the NODE_CONFIG_DIR is super important, can be absolute or relative
refer to https://github.com/lorenwest/node-config/wiki/Configuration-Files
module.exports = {
  apps : [
 {
     name      : 'process-name',
      script    : './app.js',
      cwd	: '/var/www/<your website name>/',
      instance_var: 'INSTANCE_ID',
      env: {
	    "PORT": 3000,
        "NODE_ENV": 'development',
        "NODE_CONFIG_DIR": "/var/www/<your website name>/config/"
      },
      env_production : {
	    "PORT": 8080,
        "NODE_ENV": 'production',
        "NODE_CONFIG_DIR": "/var/www/<your website name>/config/"
      }
    }
  ]
};
5- $ pm2 start pm2.config.js --env production

**Comment by trongvnau** [comment] 2017-08-07 21:32
@vmarchaud I am using v2.6.1 and i can confirm that i don't need an empty default-0.js/json file.
instance_var and NODE_CONFIG_DIR settings are important to fix the issue. I have updated my comment, thanks.
