### ISSUE TITLE
PM2 Monit 100% CPU usage

### ISSUE THREAD

**Issue by killedWithFire9001** [Unitech/pm2#2793] opened 2017-03-25 22:55 UTC
#### Actual behaviour

... pm2 monit consuming all available resources

#### Steps to reproduce

... `pm2 monit`

#### Software versions used

```
OS         : CentOS / CloudLinux  `3.10.0-427.36.1.lve1.4.40.el7.x86_64 `
node.js    : v7.7.4
PM2        : v2.4.2
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
2017-03-25 23:30:34: ===============================================================================
2017-03-25 23:30:34: --- New PM2 Daemon started ----------------------------------------------------
2017-03-25 23:30:34: Time                 : Sat Mar 25 2017 23:30:34 GMT+0100 (CET)
2017-03-25 23:30:34: PM2 version          : 2.4.2
2017-03-25 23:30:34: Node.js version      : 7.7.4
2017-03-25 23:30:34: Current arch         : x64
2017-03-25 23:30:34: PM2 home             : /root/.pm2
2017-03-25 23:30:34: PM2 PID file         : /root/.pm2/pm2.pid
2017-03-25 23:30:34: RPC socket file      : /root/.pm2/rpc.sock
2017-03-25 23:30:34: BUS socket file      : /root/.pm2/pub.sock
2017-03-25 23:30:34: Application log path : /root/.pm2/logs
2017-03-25 23:30:34: Process dump file    : /root/.pm2/dump.pm2
2017-03-25 23:30:34: Concurrent actions   : 2
2017-03-25 23:30:34: SIGTERM timeout      : 1600
2017-03-25 23:30:34: ===============================================================================
2017-03-25 23:30:34: Starting execution sequence in -fork mode- for app name:SinonDiscordBot id:0
2017-03-25 23:30:34: App name:SinonDiscordBot id:0 online
2017-03-25 23:30:56: Starting execution sequence in -fork mode- for app name:SinonTwitchBot id:1
2017-03-25 23:30:56: App name:SinonTwitchBot id:1 online
2017-03-25 23:31:10: Starting execution sequence in -fork mode- for app name:SinonOsuBot id:2
2017-03-25 23:31:10: App name:SinonOsuBot id:2 online
2017-03-25 23:31:32: Starting execution sequence in -fork mode- for app name:SinonApiBot id:3
2017-03-25 23:31:32: App name:SinonApiBot id:3 online

```
i have 4 node applications on monit, i also notice high CPU usage on my other server with 2 applications but this is causing a lockup of the system.

can provide more information on request

**Comment by p-j** [comment] 2017-04-14 08:07
I can confirm this bug, we are currently running ~80 node processes handled by PM2 on a large server and if I run `pm2 monit` it will start, almost freeze, and running `htop` on another terminal will show one CPU at 100% running `pm2 monit`.
`pm2 monit` in this situation is unusable (not possible to move around with arrow keys etc...)

We are running on a Debian 8 with node v7.3.0 and pm2 v2.4.4

**Comment by shivahn** [comment] 2017-05-16 09:40
The PM2 consumes 100% CPU usage and apps gets disappeared from list.  

We are running this in

PM2 version:  2.4.2
OS : Windows 7
RAM Memory: 8GB
Node: 4.1.1 (stable)

**Comment by vmarchaud** [comment] 2017-05-20 23:27
For anyone having the problem while we are investigating, you can use the old one interface using `pm2 imonit`

**Comment by killedWithFire9001** [comment] 2017-06-15 18:13
@vmarchaud thanks for that, that helps

just an update, im still getting this issue but much less impact-full bouncing between 10% and 80% usage on my dual core, im now using node v8.1.0

**Comment by vmarchaud** [comment] 2017-06-15 22:09
We were investigating the problem and didn't find a root case, we need more time to make a decision on what to do to fix this issue.

**Comment by dman777** [comment] 2017-07-08 06:47
Is it the monitor itself eating the cpu or the log that scrolls? I tend to think it's the log that scrolls and when it becomes long enough, it forces expensive redraws on the terminal graphics.

**Comment by vmarchaud** [comment] 2017-07-08 10:59
@dman777 from my research it as a low impact on performance, it was basically eating CPU without any update rendered on the screen.

**Comment by dman777** [comment] 2017-07-08 15:36
I did a test with pm2 monit:

1) overnight - app logs every 3 seconds.... morning time cpu was pegged at 14%
2) 2nd overnight - logging disabled. cpu was about 1%

**Comment by mathewmeconry** [comment] 2017-08-07 11:18
I can confirm this bug too.
I worte a little test script which does nearly nothing
```javascript
setInterval(() => {
    console.log('foo');
}, 250)
```
Scaled it up to 2 process per core:
![image](https://user-images.githubusercontent.com/4057473/29024510-ac2d6382-7b72-11e7-8e82-5bbff7ae27ba.png)

Then I started pm2 monit and it started 6 processes which consumed together around 18% CPU 
![image](https://user-images.githubusercontent.com/4057473/29024544-d395b1ae-7b72-11e7-9f0f-ced47d8c1bd4.png)

**Comment by killedWithFire9001** [comment] 2017-08-20 21:16
this is no longer an issue for me, tho i do some times see large usage but normally clears after some time.
@dman777 logging quantity made no difference for me in the past, i print very minimal logs to console, the alternative suggested `imonit` is all i need anyways and i still use that tho the error has cleared for me

**Comment by killedWithFire9001** [comment] 2017-08-23 14:57
woke up this morning to the cpu usage of the machine slowly been creeping up over time, this issue has returned
![image](https://user-images.githubusercontent.com/8790525/29622544-a44d2e62-881b-11e7-8260-dd17e38adeeb.png)
relaunching the `pm2 monit` cleared the issue but i still cant pin whats causing it, in that time gap around 100 lines war printed to the console with 6 active node applications

**Comment by killedWithFire9001** [comment] 2017-08-23 15:47
just updating server property's too as they have changed since original post

```
OS         : CentOS `3.10.0-514.26.2.el7.x86_64`
node.js    : v8.2.1
PM2        : v2.6.1
```

**Comment by paperab** [comment] 2017-09-06 22:14
_pm2 monit_ is still reaching 100% of cpu, no logging, screen unresponsive. 
What is found by the investigation?

**Comment by vcarel** [comment] 2017-11-22 09:08
I confirm on our side too. PM2 2.7.1 and 2.7.2
On Centos (AWS servers) or my own Desktop (Ubuntu 17.04).

**Comment by CineXMike** [comment] 2017-11-29 12:56
I confirm this on Windows server 2012.

**Comment by bladefist** [comment] 2017-12-12 16:11
Can confirm in v2.8.0 still freezing.  Ubuntu 16.

**Comment by mathewmeconry** [comment] 2017-12-13 15:26
can confirm in v2.8.0 on Debian Jessie fully patched.
freeze after 14m and average cpu consumption of 25% on a 4 core system with 5 processes

**Comment by adamkaplan** [comment] 2017-12-15 05:25
Still on v2.9.1 Ubuntu 16. Any significant log rendering in monit hastens the crash

**Comment by vmarchaud** [comment] 2017-12-15 10:10
We are aware of this problem, but we don't have time to handle this so if anyone want to make some research, here is the class that handle the `pm2 monit` command : https://github.com/Unitech/pm2/blob/master/lib/API/Dashboard.js

**Comment by adamkaplan** [comment] 2017-12-15 16:25
Totally understand! Do you have any ideas/hints for us to start with?

My initial guess is something about this code block might be overloading the rendering engine:
https://github.com/Unitech/pm2/blob/master/lib/API/Dashboard.js#L357-L365

I haven't coded with Blessed before, but a quick scan of the README showed an element made specifically for displaying infinite log data:
https://github.com/chjj/blessed#log-from-scrollabletext

At first glance, looks like the Dashboard `logBox` is a regular box text box. Changing to a Blessed Log instead might just fix the issue.

**Comment by vmarchaud** [comment] 2017-12-15 16:55
@adamkaplan I already inspected the problem few month ago but didn't found something in few dozens of minutes, if you can test and make a PR if its the right fix, we will merge it :)

**Comment by Antonhansel** [comment] 2019-03-12 11:08
I'm digging up this old issue to report that as March 12 2019 on a fresh ubuntu/node/npm/pm2 install this still happens, was a fix found in the meantime ?
![image](https://user-images.githubusercontent.com/4123811/54195671-9a51b880-44bf-11e9-8b22-1a7e7cabf460.png)

**Comment by dbonnell** [comment] 2019-03-21 05:58
Definitely not fixed.  I've just experienced this problem with both monit and log.

I accidentally left pm2 monit running overnight two days ago and yesterday morning the server was very slow and top showed pm2 using 96% CPU constantly.  I killed it, back to normal.

Last night I accidentally left pm2 log running overnight and today the server was down. I don't think it was a crash but Google Compute Engine stopping it, as when I went to check I found it was stopped with the helpful notice "This instance has had high CPU and memory utilisation recently. Consider switching to the machine the type to X".

**Comment by Unitech** [comment] 2019-04-05 13:55
fixed, now the logs stream array is fixed size, will be released soon

**Closed by Unitech** 2019-04-05 13:55 UTC
Labels: P3: Medium, S: Backlog, SYS: CLI, T: Enhancement

**Comment by smchinna** [comment] 2020-05-31 13:17
I'm also facing the issue with pm2 is consuming 100% CPU.

Version Details:
  pm2 ---> 4.4.0
  node ---> v12.16.3
  npm  ---> 6.14.4

**Comment by dftossem** [comment] 2021-07-07 04:22
Same here. Version details:
Node: v15.14.0
npm: v15.14.0
pm2: 5.1.0
