### ISSUE TITLE
PM2 logs raw not presenting all logs

### ISSUE THREAD

**Issue by GDownes** [Unitech/PM2#1277] opened 2015-05-15 08:32 UTC
Using the raw flag on the pm2 logs command is not working, and outputting nothing.

**Comment by jshkurti** [comment] 2015-05-15 10:45
Did you `pm2 logs --raw` before launching your app or after ?

**Comment by GDownes** [comment] 2015-05-15 12:04
After launching the app

**Comment by jshkurti** [comment] 2015-05-15 13:12
Any clue on how to reproduce this bug ?
It works just fine on my machine. :/
Does `pm2 logs` without the --raw flag work ?

**Comment by GDownes** [comment] 2015-05-15 14:54
I've included a picture of the behaviour I'm seeing.

From this you can see that the 'pm2 logs' command features more information including old(pre to running the command) logs we as 'pm2 logs --raw' only features logs ingested after the command is ran. I'll look into this more.

![image](https://cloud.githubusercontent.com/assets/507905/7655313/8c566692-fb1a-11e4-9dc7-db471768ea01.png)

**Comment by jshkurti** [comment] 2015-05-15 15:05
Oh, that's intended :)

**Comment by GDownes** [comment] 2015-05-15 15:06
Is there a way to get the same behaviour for the raw flag?

**Comment by jshkurti** [comment] 2015-05-15 15:08
Yeah, I will implement it.
It will work like this `pm2 logs --raw --lines=20`
I'll keep you in touch when it's ready ;)

**Comment by GDownes** [comment] 2015-05-15 15:09
Thanks

**Comment by jshkurti** [comment] 2015-05-17 16:50
It's done :)
`npm i -g git://github.com/Unitech/PM2#development`
Otherwise it will be included in PM2 v0.12.15 coming soon ;)

**Closed** 2015-05-17 17:03 UTC
