### ISSUE TITLE
Cluster mode beta warning when using Node.js v10.10.0

### ISSUE THREAD

**Issue by awgy** [Unitech/pm2#3911] opened 2018-09-14 02:05 UTC
https://github.com/Unitech/pm2/blob/ea4bc96d82703545c185e3d3b1d55e8a537687dc/lib/Common.js#L737

It looks like the process version match linked above was intended for a much older version of Node.js and the regex would just need a minor tweak to prevent matching against this release.  Maybe something like:

`process.version.match(/^v0.10/)`

Or consider removing the warning altogether.

**Comment by wallet77** [comment] 2018-09-14 16:02
We will remove this part, node 0.10 was dropped in pm2 v3.X
It's also a duplicate of https://github.com/Unitech/pm2/issues/3910, so I close this one.

**Closed by wallet77** 2018-09-14 16:02 UTC
