### ISSUE TITLE
Mismatched npm sha hash when installing on Node 8 or 9?

### ISSUE THREAD

**Issue by chazzmoney** [Unitech/pm2#3417] opened 2018-01-19 23:34 UTC
## What's going wrong?
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-QFUCsAfzGcP0cXXER0UnMA8qta0= integrity checksum failed when using sha1: wanted sha1-QFUCsAfzGcP0cXXER0UnMA8qta0= but got sha512-zr6QQnzLt3Ja0t0XI8gws2kn7zV2p0l/D3kreNvS6hFZhVU5g+uY/30l42jbgt0XGcNBEmBDGJR71J692V92tA==. (260 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

## How could we reproduce this issue?
nvm install 8
npm install -g pm2

## Supporting information
Found in two different environments:
(Mac OS X) Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
(Amazon Linux 2) Amazon Linux release 2.0 (2017.12) LTS Release Candidate

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__


                          Community Edition

            Production Process Manager for Node.js applications
                     with a built-in Load Balancer.


                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/


                        -------------

[PM2] Spawning PM2 daemon with pm2_home=/home/ec2-user/.pm2
[PM2] PM2 Successfully daemonized
===============================================================================
--- PM2 REPORT (Fri Jan 19 2018 23:33:30 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.9.1
node version         : 8.9.4
node path            : /home/ec2-user/.nvm/versions/node/v8.9.4/bin/pm2
argv                 : /home/ec2-user/.nvm/versions/node/v8.9.4/bin/node,/home/ec2-user/.nvm/versions/node/v8.9.4/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ec2-user
uid                  : 1000
gid                  : 1000
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.9.1
node version         : 8.9.4
node path            : /home/ec2-user/.nvm/versions/node/v8.9.4/bin/pm2
argv                 : /home/ec2-user/.nvm/versions/node/v8.9.4/bin/node,/home/ec2-user/.nvm/versions/node/v8.9.4/bin/pm2,report
argv0                : node
user                 : ec2-user
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 1
freemem              : 191569920
totalmem             : 1041055744
home                 : /home/ec2-user
===============================================================================
```

**Comment by wallet77** [comment] 2018-01-23 16:49
Hi,

It seems to be an npm issue, not directly related to pm2.
Probably a duplicate of : [npm/npm/issues/17146](https://github.com/npm/npm/issues/17146)
Please tell us if one of the solutions works for you.

**Closed by wallet77** 2018-01-23 16:49 UTC

**Comment by dfuentes77** [comment] 2018-01-31 17:29
The only applicable and potential solutions was to force the npm cache to clear and the removal of ~/.npm, and neither helped me.  Seems unique to when I do the `npm install -g pm2` on Amazon Linux (not 2)

**Comment by JamesRamm** [comment] 2018-02-27 12:59
I also have the same problem when running `npm install -g pm2` in docker (build). This is within the `node:alpine` image. 
clearing cache etc doesn't change anything

**Comment by zamirkhan** [comment] 2018-07-20 04:57
Same issue with Node v9.10.1 on Mac OSX and AWS Linux. Clearing npm cache does not solve it.
