### ISSUE TITLE
Inspect process sends SIGABRT

### ISSUE THREAD

**Issue by maximeloizeau** [Unitech/pm2#3904] opened 2018-09-10 21:23 UTC
## What's going wrong?
When enabling debug mode on a process, after connecting the debugger (VS Code, Chrome debugger) the process is instantly killed and the pm2 logs display:
```
PM2        | App name:test id:1 disconnected
PM2        | App [test] with id [1] and pid [6715], exited with code [0] via signal [SIGABRT]
```

This issue doesn't happen when running the same application without pm2.

## How could we reproduce this issue?
- Use pm2 inspect (or kill -s SIGUSR1)
- Observe the process enabling the debugging
- Connect to port 9229 with debugger
- Observe process being killed and then restarted by pm2

## Supporting information
Running on AWS EC2 instance configured via Beanstalk
```
===============================================================================
--- PM2 REPORT (Mon Sep 10 2018 21:19:44 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.0
node version         : 8.9.3
node path            : /opt/elasticbeanstalk/node-install/node-v8.9.3-linux-x64/bin/node
argv                 : /opt/elasticbeanstalk/node-install/node-v8.9.3-linux-x64/bin/node,/var/app/current/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : nodejs
uid                  : 496
gid                  : 494
uptime               : 258min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.0
node version         : 8.9.3
node path            : /opt/elasticbeanstalk/node-install/node-v8.9.3-linux-x64/bin/node
argv                 : /opt/elasticbeanstalk/node-install/node-v8.9.3-linux-x64/bin/node,/var/app/current/node_modules/pm2/bin/pm2,report
argv0                : /opt/elasticbeanstalk/node-install/node-v8.9.3-linux-x64/bin/node
user                 : nodejs
uid                  : 496
gid                  : 494
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
cpus nb              : 4
freemem              : 14562062336
totalmem             : 16828456960
home                 : /tmp
===============================================================================
--- PM2 list -----------------------------------------------
┌───────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬───────┬────────────┬────────┬──────────┐
│ App name          │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu   │ mem        │ user   │ watching │
├───────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼───────┼────────────┼────────┼──────────┤
│ test           ⏱ │ 0  │ cluster │ 14946 │ online │ 9       │ 80s    │ 18.1% │ 691.0 MB   │ nodejs │ disabled │
│ test           ⏱ │ 1  │ cluster │ 14661 │ online │ 9       │ 7m     │ 4.3%  │ 322.6 MB   │ nodejs │ disabled │
│ test           ⏱ │ 2  │ cluster │ 14678 │ online │ 3       │ 7m     │ 2.7%  │ 272.3 MB   │ nodejs │ disabled │
│ test           ⏱ │ 3  │ cluster │ 14683 │ online │ 3       │ 7m     │ 7.3%  │ 401.7 MB   │ nodejs │ disabled │
└───────────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴───────┴────────────┴────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌───────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬────────────┬────────┬──────────┐
│ App name          │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user   │ watching │
├───────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼────────────┼────────┼──────────┤
│ test           ⏱ │ 0  │ cluster │ 14946 │ online │ 9       │ 80s    │ 0%  │ 691.0 MB   │ nodejs │ disabled │
│ test           ⏱ │ 1  │ cluster │ 14661 │ online │ 9       │ 7m     │ 0%  │ 322.6 MB   │ nodejs │ disabled │
│ test           ⏱ │ 2  │ cluster │ 14678 │ online │ 3       │ 7m     │ 0%  │ 272.3 MB   │ nodejs │ disabled │
│ test           ⏱ │ 3  │ cluster │ 14683 │ online │ 3       │ 7m     │ 0%  │ 401.7 MB   │ nodejs │ disabled │
└───────────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴────────────┴────────┴──────────┘
```

**Comment by wallet77** [comment] 2018-09-11 07:57
I think it's a duplicate of https://github.com/Unitech/pm2/issues/3785

**Comment by maximeloizeau** [comment] 2018-09-11 08:06
Thank you for linking this issue, it looks like it. I will try what you mentioned in the other thread.

**Comment by Unitech** [comment] 2018-09-11 08:51
@maximeloizeau try upgrading pm2 to the latest version, this issue has been addressed

**Closed by Unitech** 2018-09-11 08:51 UTC
