### ISSUE TITLE
Process does not stop on script exit

### ISSUE THREAD

**Issue by hufftheweevil** [Unitech/pm2#3790] opened 2018-07-12 15:19 UTC
## What's going wrong?
I recently upgraded from 2.10.4 to 3.0.0 and it seems there has been a major change in how processes are handled when the script exits. In previous versions, the process would stop after the script was complete. And if `autorestart` was set to `false` then, of course, it would remain stopped. But it seems with the new version that process remains online even if the script exits. And I can't find any documentation in the changelog, or elsewhere, that explains this.

## How could we reproduce this issue?
Create an empty file named `test.js` and then run `pm2 start test.js`. Use `pm2 monit` or `pm2 list` to see that the process remains online, even though there should be no reason for it to be.

## Supporting information

```
===============================================================================
--- PM2 REPORT (Thu Jul 12 2018 11:16:17 GMT-0400 (Eastern Daylight Time)) ----
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.0
node version         : 8.11.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\myname\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.0
node version         : 8.11.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\myname\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : myname
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
cpus nb              : 4
freemem              : 9152544768
totalmem             : 17066647552
home                 : C:\Users\myname
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬────────┬────────┬─────────┬────────┬─────┬───────────┬────────┬──────────┐
│ App name │ id │ mode │ pid    │ status │ restart │ uptime │ cpu │ mem       │ user   │ watching │
├──────────┼────┼──────┼────────┼────────┼─────────┼────────┼─────┼───────────┼────────┼──────────┤
│ test     │ 0  │ fork │ 138968 │ online │ 0       │ 3s     │ 0%  │ 25.8 MB   │ myname │ disabled │
└──────────┴────┴──────┴────────┴────────┴─────────┴────────┴─────┴───────────┴────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\myname\.pm2\pm2.log last 20 lines:
PM2        | [2018-07-12T11:16:13.517Z] PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | [2018-07-12T11:16:13.518Z] PM2 log: Time                 : Thu Jul 12 2018 11:16:13 GMT-0400 (Eastern Daylight Time)
PM2        | [2018-07-12T11:16:13.518Z] PM2 log: PM2 version          : 3.0.0
PM2        | [2018-07-12T11:16:13.518Z] PM2 log: Node.js version      : 8.11.1
PM2        | [2018-07-12T11:16:13.518Z] PM2 log: Current arch         : x64
PM2        | [2018-07-12T11:16:13.518Z] PM2 log: PM2 home             : C:\Users\myname\.pm2
PM2        | [2018-07-12T11:16:13.518Z] PM2 log: PM2 PID file         : C:\Users\myname\.pm2\pm2.pid
PM2        | [2018-07-12T11:16:13.518Z] PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | [2018-07-12T11:16:13.519Z] PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | [2018-07-12T11:16:13.519Z] PM2 log: Application log path : C:\Users\myname\.pm2\logs
PM2        | [2018-07-12T11:16:13.519Z] PM2 log: Process dump file    : C:\Users\myname\.pm2\dump.pm2
PM2        | [2018-07-12T11:16:13.519Z] PM2 log: Concurrent actions   : 2
PM2        | [2018-07-12T11:16:13.519Z] PM2 log: SIGTERM timeout      : 1600
PM2        | [2018-07-12T11:16:13.519Z] PM2 log: ===============================================================================
PM2        | [2018-07-12T11:16:13.560Z] PM2 log: Starting execution sequence in -fork mode- for app name:test id:0
PM2        | [2018-07-12T11:16:13.569Z] PM2 log: App name:test id:0 online
```

**Comment by wallet77** [comment] 2018-07-12 15:32
Hi @hufftheweevil 

Thanks for information : it's clearly a duplicate of : https://github.com/Unitech/pm2/issues/3779
I'm working on it : https://github.com/keymetrics/pm2-io-apm/issues/145

**Closed by wallet77** 2018-07-12 15:32 UTC
