### ISSUE TITLE
PM2 executed from within node inherits command line arguments

### ISSUE THREAD

**Issue by stevekeiser** [Unitech/pm2#941] opened 2015-01-15 18:18 UTC
This is a weird one. Hopefully I can explain clearly. Let's say that I run `pm2 start a.js -- 3000` and _a.js_ calls `require('child_process').exec('pm2 start b.js -- 4000')` then _b.js_ will receive 3000 as it's argument instead of 4000, as expected. This is true even if _a.js_ uses the API, e.g. `pm2.start('b.js', {rawArgs: ['--', 4000]})`. The child process seems to inherit the command line arguments of the parent.

**Comment by catchdave** [comment] 2015-02-04 07:47
I'm having the same problem too. When the parent process is run with command line args, the child processes started via `pm2.start()` have the arguments ignored and uses the parents arguments instead.

Example:
`pm2 start processes.json`

**processes.json:**

    { apps: [
        { name: "loader.js", args: ["--debug", "--path=/var/foo"] }
    ]}

**loader.js**
    
    var curProcess = 'foo'; // this comes from somewhere else
    var params = {
        name: curProcess,
        rawArgs: ['--', "--bar"]
    };
    pm2.start('sub-process.js', params);

In the above example, pm2 will start the sub process as `pm2 start sub-process.js --debug,"--path=/var/foo` instead of the expected `pm2 start sub-process.js --bar`.

Note, I have to use rawArgs here to workaround another pm2 bug specified here: https://github.com/Unitech/pm2/issues/590

**Comment by catchdave** [comment] 2015-02-10 18:35
@Unitech : Any ideas about this bug?

**Comment by Tjatse** [comment] 2015-02-11 06:47
I've confirmed this bug. Just need time to fix it.

**Comment by michAtEl** [comment] 2015-04-06 19:32
I've the same problem. It happens only, if the process, that calls pm2.start() is running in pm2. If I start the process, that calls pm2.start(), without pm2, everything works fine.

**Comment by mathieumante** [comment] 2015-05-13 12:35
+1
I've the same problem, and also with restart.
Do you have any ideas about this bug?

**Comment by jshkurti** [comment] 2015-05-21 14:22
Can you try `npm i -g git://github.com/Unitech/PM2#development` ?
I think this might have been fixed by https://github.com/Unitech/PM2/pull/1282/files#diff-96936c803a7f9ae2c51530cc944a8cceR324

**Comment by Unitech** [comment] 2016-11-23 08:25
Issue fixed since PM2 1.1.3

```
$ npm install pm2@latest -g
$ pm2 update
```

**Closed by Unitech** 2016-11-23 08:25 UTC
Labels: bug
