### ISSUE TITLE
Watch & reload resets to disabled bug

### ISSUE THREAD

**Issue by nodesocket** [Unitech/pm2#2441] opened 2016-10-13 03:43 UTC
#### Expected behavior

Watch & reload flag stays persistent when an application is stopped and started manually. Application configured using `.yml` file.

#### Actual behavior

Watch & reload is set when an application is initially started, howerver if you run:

````shell
pm2 stop api-dev
pm2 start api-dev
````

You'll see watching has been reset to disabled.

#### Steps to reproduce

Start application with a `.yml` similar to:

````yaml
apps:
  - name: 'api-dev'
    cwd: /home/node/api
    script: ./api.js
    args: '--config config-dev.json'
    watch: true
    autorestart: true
    exec_mode: 'cluster'
    instances: -1
    combine_logs: true
````

Then run:

````shell
pm2 stop api-dev
pm2 start api-dev
pm2 info api-dev
````

#### Software versions used

**OS**: Ubuntu 16.04.1 LTS
**Node.js**: v6.5.0
**PM2**: 2.0.18

**Comment by nodesocket** [comment] 2016-10-13 03:44
Direct terminal proof:

````
➜  api git:(master) pm2 start pm2-dev.yml
[PM2][WARN] Applications api-dev not running, starting...
[PM2] App [api-dev] launched (1 instances)
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ api-dev  │ 0  │ cluster │ 27292 │ online │ 0       │ 0s     │ 74% │ 24.3 MB   │  enabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
➜  api git:(master) pm2 stop 0
[PM2] Applying action stopProcessId on app [0](ids: 0)
[PM2] [api-dev](0) ✓
┌──────────┬────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────────┐
│ App name │ id │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ watching │
├──────────┼────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────────┤
│ api-dev  │ 0  │ cluster │ 0   │ stopped │ 0       │ 0      │ 0%  │ 0 B    │  enabled │
└──────────┴────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
➜  api git:(master) pm2 start 0
[PM2] Applying action restartProcessId on app [0](ids: 0)
[PM2] [api-dev](0) ✓
[PM2] Process successfully started
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ api-dev  │ 0  │ cluster │ 27348 │ online │ 0       │ 0s     │ 71% │ 24.2 MB   │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
````

**Comment by soyuka** [comment] 2016-10-13 06:41
Yeah, I don't think this is wanted. To me, `pm2 stop 0` should stop watching because it might just get restarted on file change, and we asked the script to stop... 

@Unitech what is the expected behaviour here?

**Comment by nodesocket** [comment] 2016-10-14 22:33
@Unitech any update?

**Comment by nodesocket** [comment] 2016-10-16 09:45
Also confirm running:

`pm2 restart 0` drops `watch & reload` to disabled even if enabled previously.

**Comment by ashwell** [comment] 2016-10-20 01:23
Somewhat related to this I was seeing processes get restarted on change after they were stopped.

Basically
```
pm2 stop proc-with-watch
*edit a file that would trigger a restart*
pm2 ls
*proc-with-watch is now running*
```

Maybe this is expected but I would think a "stopped" process shouldn't be restarted regardless of the watch setting. I can provide more information if needed.

**Comment by Unitech** [comment] 2016-10-24 11:12
bug reproduced, inspecting

**Comment by Unitech** [comment] 2016-10-26 16:39
Fix is available:

```bash
$ npm install pm2@next -g
$ pm2 update
```

Closing in favor of #2471

**Closed by Unitech** 2016-10-26 16:39 UTC
Labels: inspecting
