### ISSUE TITLE
Not all apps showing up when running list

### ISSUE THREAD

**Issue by ScriptPup** [Unitech/pm2#2177] opened 2016-05-18 19:06 UTC
Hi there,

I've run into an... interesting... problem. I'm running pm2 using a .json configuration file. This works pretty well. However, I'm now trying to write a processes to allow admins to restart the server (all apps) from the webapp.

To do this I'm using node's child_process functionality to start a .bat file. I'm starting it using the START command so that the process branch isn't ended when the node server ends, this works fine. 

Inside the .bat file I am using CALL `pm2 kill` to end all processes (using restart sends the apps into an unending EADDRINUSE error loop...). 

I'm using call so that the terminal returns after running the command. Then I run `pm2 start .\myapp.json` (this is the same command I use to start the apps from the outside). I've tried that using CALL and without using call.

The nature of the problem is this... All apps start and I can see them in taskmanager (running on windows 10 btw) under my user. But only the last app started shows up when I run `pm2 list`. I also cannot use the id (0,1, or 2 if I have four apps running) to show details, stop, etc. 

From what I've found it's likely that the apps are starting in the wrong user context. So I tried using `pm2 start .\myapp.json -u myuser`. This made no difference... So to summarize... I think that for some reason pm2 is not starting the apps in the correct context when they're called from a .bat file started by the child_process feature of node. Well, all but one is started in the wrong context... Not sure why.

Any insight/ideas would be very helpful. 

Note: Haven't tried this using a bash script on any linux distros yet.

**Comment by ScriptPup** [comment] 2016-05-18 20:55
UPDATE: 
When I run `pm2 show myappname` for the app that IS listed when I run `pm2 list` get an error message... 
`C:\Users\ethan\AppData\Roaming\npm\node_modules\pm2\lib\CLI\CliUx.js:83
    throw new Error(pm2_env.created_at + ' is not a valid date: '+e.message, e.fileName, e.lineNumber);
    ^

Error: 1463604518014 is not a valid date: Invalid time value
    at Object.UX.describeTable (C:\Users\ethan\AppData\Roaming\npm\node_modules\pm2\lib\CLI\CliUx.js:83:11)
    at C:\Users\ethan\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:1450:12
    at Array.forEach (native)
    at C:\Users\ethan\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:1449:18
    at C:\Users\ethan\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\client.js:45:10
    at Parser.<anonymous> (C:\Users\ethan\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\req.js:67:8)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Parser._write (C:\Users\ethan\AppData\Roaming\npm\node_modules\pm2\node_modules\amp\lib\stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)`

When I try the same thing using the names of the other apps (which are running, but not in the list) a message saying the app doesn't exist is returned.

**Comment by romandubrov** [comment] 2016-06-09 13:15
same for me

`$ pm2 show 0
/usr/lib/node_modules/pm2/lib/CLI/CliUx.js:83
    throw new Error(pm2_env.created_at + ' is not a valid date: '+e.message, e.fileName, e.lineNumber);
    ^

Error: 1465475983708 is not a valid date: Invalid time value
    at Object.UX.describeTable (/usr/lib/node_modules/pm2/lib/CLI/CliUx.js:83:11)
    at /usr/lib/node_modules/pm2/lib/CLI.js:1450:12
    at Array.forEach (native)
    at /usr/lib/node_modules/pm2/lib/CLI.js:1449:18
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:307:12)
`

**Comment by gtarun** [comment] 2016-06-13 09:15
Even I'm facing the same issue, whenever I m trying to start  any app.js 
**pm2 list shows the process as online but it actually not working.**


/home/deploy/.nvm/versions/node/v4.4.5/lib/node_modules/pm2/lib/CLI/CliUx.js:83
    throw new Error(pm2_env.created_at + ' is not a valid date: '+e.message, e.fileName, e.lineNumber);
    ^

Error: 1465800255220 is not a valid date: Invalid time value
    at Object.UX.describeTable (/home/deploy/.nvm/versions/node/v4.4.5/lib/node_modules/pm2/lib/CLI/CliUx.js:83:11)
    at /home/deploy/.nvm/versions/node/v4.4.5/lib/node_modules/pm2/lib/CLI.js:1450:12
    at Array.forEach (native)
    at /home/deploy/.nvm/versions/node/v4.4.5/lib/node_modules/pm2/lib/CLI.js:1449:18
    at /home/deploy/.nvm/versions/node/v4.4.5/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/deploy/.nvm/versions/node/v4.4.5/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/home/deploy/.nvm/versions/node/v4.4.5/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:300:12)

**Comment by huluoyang** [comment] 2016-06-22 08:51
same for me too.
pm2 list shows the process as online but it actually not working.
pm2 show 0
throw new Error(pm2_env.created_at + ' is not a valid date: '+e.message, e.fileName, e.lineNumber);
i have downgrade pm2 version from 1.1.3 to 1.1.1.
question also happen.
is there any body can solve the question?
thanks.

**Comment by gtarun** [comment] 2016-07-09 06:01
shifted back to forever, its working like charm


On Wed, Jun 22, 2016 at 2:21 PM, huluoyang <notifications@github.com> wrote:

> same for me too.
> pm2 list shows the process as online but it actually not working.
> pm2 show 0
> throw new Error(pm2_env.created_at + ' is not a valid date: '+e.message,
> e.fileName, e.lineNumber);
> i have downgrade pm2 version from 1.1.3 to 1.1.1.
> question also happen.
> is there any body can solve the question?
> thanks.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Unitech/pm2/issues/2177#issuecomment-227682088>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFJ6GxuRCTvy4IoqLKIL4A5cXMqyLUG6ks5qOPePgaJpZM4Ihmb0>
> .
>



-- 

Best,

*Tarun Gupta*,
Software Engineer | VenturePact Technology <http://venturepact.com/>
t:+91 98889 81003
<https://www.facebook.com/tarungupta990>
<https://plus.google.com/+TarunGupta24>  <https://twitter.com/tarungupta003>

http://about.me/gtarun
http://blogs.tarungupta.info

**Comment by vmarchaud** [comment] 2016-07-09 14:19
@huluoyang Could you try with the dev branch of pm2 (```npm install -g pm2#development```) and tell me if the issue is still happening ?

**Comment by Unitech** [comment] 2016-07-11 11:55
@gtarun @huluoyang @romandubrov issues have been fixed on PM2 v2 (development branch) when starting script that interact with PM2 inside PM2.

Just commented that weird throw about a malformated date.

If you could please provide me a way to reproduce that bug it could be VERY helpful,

Thanks

**Comment by romandubrov** [comment] 2016-07-11 12:14
I got that message when tried to manage pm2 processes using pm2 node.js module. module is interfering with pm2 somehow and corrupts stored data. unfortunately can't test it now as already went off to production with another solution.

also a note that could be interesting: when pm2 is called from nodejs using exec (not using module), env goes to async as is. then it is being converted to json and there we are getting an exception regarding circular object because env contains a ref to itself. it was easy to fix this passing {env: {HOME: process.env.HOME}} to exec, but it's quite hard to find, so it would be great if pm2 will clean up external data it passes to async

**Comment by Unitech** [comment] 2016-07-11 12:28
@romandubrov these issues has been succesfully fixed on pm2 v2 (see https://github.com/Unitech/pm2/issues/2077) :)

**Comment by ScriptPup** [comment] 2016-07-18 18:54
After updating to the latest development version, I'm still experiencing this issue. I'm glad if it's been fixed for some folks, but I want to make sure everyone is aware there's still a problem...

This image shows what's visible before and after restarting my pm2 instance with a script. It also verifies the installed version.
![image](https://cloud.githubusercontent.com/assets/6163646/16926616/16d507ac-4cef-11e6-9b4a-bb46a31063e6.png)

**Comment by soyuka** [comment] 2016-07-19 06:27
@ScriptPup can you provide a way to reproduce your issue? Thanks!

**Comment by ScriptPup** [comment] 2016-08-02 18:40
Hi soyuka,
Absolutely. Set up a few node.js servers, then in one of the services have a function to call pm2.restart(); You will see the same behavior. (though I'd recommend only calling it once, since you could get caught in a loop :) )

I wish I had a simple configuration I could just post for you, but it's a large project that I'm working on at the moment.

**Comment by ScriptPup** [comment] 2016-08-02 18:41
Alternatively, set up a few node services, then call a .bat file with the following lines in them (from within a node.js service)

```
CALL pm2 kill
CALL pm2 start
CALL pm2 start .\LabMan.json
exit;
```

**Comment by vmarchaud** [comment] 2016-09-24 15:26
the issue [should be fixed](https://github.com/Unitech/pm2/commit/55d910b144e9988d884773e01cc2f5f11a1fb5d2) in version `2.0.12`, can you verify this with your setup @ScriptPup ?

**Closed** 2017-01-13 10:53 UTC
