### ISSUE TITLE
Apps are not started after reboot

### ISSUE THREAD

**Issue by slavafomin** [Unitech/pm2#1891] opened 2016-01-15 09:20 UTC
Hello there!

Thank you for your great work!

However, I'm encountering a situation where apps added to PM2 are not restarted after a server reboot. The PM2's list is empty. I'm running PM2 under a custom `deploy` user in Ubuntu OS.

I'm doing the following as a `deploy` user:

`$ pm2 start /var/www/app-1/app.js --name app-1 -- --prod`
`$ pm2 start /var/www/app-2/app.js --name app-2 -- --prod`
`$ pm2 start /var/www/app-3/app.js --name app-3 -- --prod`

Then I do: `sudo env PATH=$PATH:/usr/local/bin pm2 startup -u deploy`

After that I do: `pm2 save` and `reboot`.

After reboot the list of apps is empty.

What could be the reason for this? Thank you!

---

```
$ cat /etc/issue
Ubuntu 15.10
```

```
# uname -a
Linux 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:48:35 UTC 2015 i686 i686 i686 GNU/Linux
```

```
$ node --version
v5.4.1
```

```
$ pm2 --version
1.0.0
```

**Comment by estliberitas** [comment] 2016-01-15 15:09
@slavafomin checkout `PM2_HOME` env variable value in startup script. Maybe that's the cause like in #1888 or #1321 or #1762

**Comment by Unitech** [comment] 2016-02-29 23:51
closing because of possible duplicate with #1035

**Closed by Unitech** 2016-02-29 23:51 UTC
