### ISSUE TITLE
Cannot install module on Windows

### ISSUE THREAD

**Issue by f-hj** [Unitech/pm2#3481] opened 2018-02-20 17:56 UTC
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
Cannot install a module on Windows

## How could we reproduce this issue?
`pm2 install pm2-server-monit`

## Supporting information
c:\Users\User\AppData\Roaming\npm\node_modules\pm2\lib\API\Modules\Modularizer.js:188
    process.chdir(process.env.HOME);
            ^

TypeError: Bad argument.
    at c:\Users\User\AppData\Roaming\npm\node_modules\pm2\lib\API\Modules\Modularizer.js:188:13
    at c:\Users\User\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by wallet77** [comment] 2018-02-21 14:23
Duplicate of #3456

**Closed** 2018-02-26 12:32 UTC
