### ISSUE TITLE
pm2-docker in watch and restart mode causes pm2 to exit sometimes

### ISSUE THREAD

**Issue by dguo** [Unitech/pm2#3206] opened 2017-10-10 20:56 UTC
## What's going wrong?
For local development, I work inside a Docker container. When I use pm2-docker with watch mode on, pm2 frequently quits after I change a file. I get the following trace:
```
0 application online, exiting
Exiting PM2
```

I did some debugging and found [this commit](https://github.com/Unitech/pm2/commit/4f8b8d6803ab3b626c7da567a093870ee10ab2bc). My guess is that there is a race condition between the setInterval in the autoExit function and the application restarting. If it doesn't restart fast enough, autoExit is triggered.

## How could we reproduce this issue?
Try pm2-docker with watch mode on, and change a file repeatedly.

## Supporting information
I saw the rationale for making autoExit the default for pm2-docker, but [the option](https://github.com/Unitech/pm2/blob/master/lib/binaries/Runtime4Docker.js#L27) is still in the CLI, even though the code [doesn't seem to check for it](https://github.com/Unitech/pm2/blob/master/lib/binaries/Runtime4Docker.js#L43). I think either the flag should be used to turn off autoExit, or it should be removed from the CLI if it doesn't actually do anything.

In the meantime, I switched to using pm2-dev, which is working so far.

```
===============================================================================
--- PM2 REPORT (Tue Oct 10 2017 20:40:41 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.1
node version         : 8.6.0
node path            : undefined
argv                 : /usr/local/bin/node,/app/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.1
node version         : 8.6.0
node path            : undefined
argv                 : /usr/local/bin/node,/app/node_modules/.bin/pm2,report
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
cpus nb              : 2
freemem              : 1549955072
totalmem             : 2096160768
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
```

**Comment by RoyHP** [comment] 2017-10-15 02:08
I am seeing the exact same behavior. Race condition; PM2 randomly exits with code 0 when the app being watched is being restarted (perhaps a check happens, seeing there's nothing running [in the middle of a restart] and PM2 exits). Naturally happens when using --auto-exit

**Comment by Unitech** [comment] 2017-10-19 13:51
Is anyone willing to do a small PR to fix this issue? That would be very appreciated 

https://github.com/Unitech/pm2/blob/master/lib/binaries/Runtime4Docker.js

**Comment by dguo** [comment] 2017-10-19 14:13
I can probably find some time to do it, but how would you like to fix it? Should we add a `--no-auto-exit` flag? The issue would still occur by default, but at least there would be a workaround.

**Comment by vmarchaud** [comment] 2017-10-22 11:26
Since the flag is already [here](https://github.com/Unitech/pm2/blob/master/lib/binaries/Runtime4Docker.js#L27), you can just do something like this : 
```
if (commander.autoExit !== false) {
 autoExit();
}
```

**Comment by clok** [comment] 2017-10-23 21:08
I am seeing this race condition as well. Very interested in seeing this fixed.

**Comment by acuntex** [comment] 2017-10-24 15:20
Seems to hang even without a watch... We currently use pm2-docker on an aws instance.
From time to time the docker container just hangs with the error message "PM2 Daemon is dead" and cannot even be killed.
Only a whole server restart fixes the issue.

**Comment by Unitech** [comment] 2017-12-14 11:44
Fixed.

Changelog: [2.9.0 CHANGELOG](https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#290)
Introduced in version: 2.9.0

Update procedure:

```bash
npm install pm2 -g
pm2 update
```

**Comment by RoyHP** [comment] 2018-01-08 21:28
I don't think it's safe to consider this resolved with the addition of the flag to disable auto exit - the intended functionality of auto-exit (which is useful for docker) still suffers from a race condition.

**Comment by erikverheij** [comment] 2018-03-05 13:06
Although the workaround works, I can confirm the root of the issue has not been resolved as of 2.10.1. 

I ran into the problem when I started using `restart_delay`. It seems like the auto-exit feature does not look for apps that are pending for a restart. 

How to reproduce?

1. Start a single app with pm2-runtime using the following config;

        // apps.js
        module.exports = {
          apps : [{
            name: 'test',
            script: 'server.js',
            instances: 1,
            restart_delay: 3000,
          }]
        };

2. Simulate a crashing app in `server.js`

       // server.js
       setTimeout(() => {
         console.log('Simulate a crashing app');
         process.exit(0);
       }, 5000);

3. Run `pm2-runtime config.js`

- Expected behavior: The app would just restart
- Actual behavior: Pm2 exits before the app restarts

**Comment by luisdavim** [comment] 2018-03-08 14:29
I'm having the same issue.

**Comment by quinn** [comment] 2018-03-24 16:17
This is definitely happening

**Comment by quinn** [comment] 2018-03-24 16:18
@Unitech Please reopen until issue is resolved

**Comment by quinn** [comment] 2018-03-24 16:20
@Unitech to further clarify this is happening on a *fresh build* from `keymetrics/pm2` docker image. So it's doubtful that whatever release you are referencing fixed anything.

**Comment by Unitech** [comment] 2018-03-29 12:42
@quinn it should be good now, just update to the latest pm2:

```
$ npm install pm2@latest -g
```

Closing, if you have any issue re-open it thanks

**Closed by Unitech** 2018-03-29 12:42 UTC
Labels: SYS: CLI, SYS: Docker, T: Bug

**Comment by erikverheij** [comment] 2018-04-13 09:59
Thanks for the update. 

I don't think the fix is really solving the underlying problem. It now waits a bit longer, but whenever you've configured `restart_delay > 4000` it will still exit the app while it shouldn't. 

Steps to reproduce;

1. Start a single app with pm2-runtime using the following config;

        // apps.config.js
        module.exports = {
          apps : [{
            name: 'test',
            script: 'server.js',
            instances: 1,
            restart_delay: 5000,
          }]
        };

2. Simulate a crashing app in `server.js`

       // server.js
       setTimeout(() => {
         console.log('Simulate a crashing app');
         process.exit(0);
       }, 5000);

3. Run `pm2-runtime apps.config.js`

- Expected behavior: The app would just restart
- Actual behavior: Pm2 exits before the app restarts


Would it be an idea to to add `cst.LAUNCH_PENDING_STATUS`? Or another solution might be that the autoexit timeout is configurable. If you want a long time between restarts you can also set a long timeout for autoexit.
