### ISSUE TITLE
Instances not working

### ISSUE THREAD

**Issue by SergeyShablenko** [Unitech/pm2#3908] opened 2018-09-12 09:57 UTC
## What's going wrong?

set `instances` to 1, but pm2 always starts max possible instances

## How could we reproduce this issue?

set instances to 1 and run pm2 start /path/to/config.js

## Supporting information

running with `pm2 start ecosystem.config.js`

```node
module.exports = {
  apps: [{
    name: 'test',
    script: './server/bin/www',
    env: {
      NODE_ENV: 'development'
    },
    env_production: {
      NODE_ENV: 'production'
    },
    instances: 2,
    exec_mode: 'cluster'
  }]
};

```

```
$ pm2 report
```
![selection_110](https://user-images.githubusercontent.com/13334277/45417532-0a0af600-b68b-11e8-92ef-e1ee4f5cf273.png)

**Comment by wallet77** [comment] 2018-09-12 14:47
Hi @SergeyShablenko 

Can't reproduce it.
But in any case you should use exec_mode: 'fork' if you want only 1 instance.

**Comment by SergeyShablenko** [comment] 2018-09-12 14:56
found a way to reproduce

it seems like pm2 caches last start, and then don`t look at config.
After I have rebooted laptop, at first start it created exact number of instances set in config, any other starts of application create same number of instances as for first run

**Comment by wallet77** [comment] 2018-09-12 15:16
Ok I got it.
So it's duplicate of : https://github.com/Unitech/pm2/issues/3742

**Closed by wallet77** 2018-09-12 15:16 UTC
Labels: Pending Closing
