### ISSUE TITLE
When pm2 considers a process up and running?

### ISSUE THREAD

**Issue by mirkods** [Unitech/pm2#2098] opened 2016-04-19 08:18 UTC
Hi everyone,
I was trying to realized a zero downtime deployment for my project and I have a question about it.
When my server starts it needs a setup time ( like for example db connection, redis connection and so on) before it's ready. So when I run the command `pm2 reload process-name` it losts some connections and I suppose this happen because pm2 thinks that the process is ready but it's not so because it is starting with its setup.

I made some tests with Apache Benchmark in order to do a real number of requests an in the meantime I run `pm2 reload all` command. This is the output:

```
Concurrency Level:      100
Time taken for tests:   65.247 seconds
Complete requests:      10000
Failed requests:        110
   (Connect: 0, Receive: 0, Length: 110, Exceptions: 0)
Non-2xx responses:      110
Total transferred:      78337000 bytes
HTML transferred:       67906376 bytes
Requests per second:    153.26 [#/sec] (mean)
Time per request:       652.472 [ms] (mean)
Time per request:       6.525 [ms] (mean, across all concurrent requests)
Transfer rate:          1172.48 [Kbytes/sec] received
```

As you can see 110 requests failed so my deployment can't be considered zero downtime.

How can I fix it? 
Is there a way to communicate to pm2 when a process is ready to accept connections?

Cheers,
Mirko

**Comment by jamiemcconnell** [comment] 2016-04-26 12:43
You could try firing `process.send('online')` which i believe signals to PM2 that your app has started and is ready.

I found exactly this problem - except i was using gracefulReload (which i now spot is going to be deprecated).
The issue is that when PM2 spawns the new process the old one is still getting traffic served to it because of NodeJS's native clustering.
By calling `old_worker.disconnect()` (along with couple of other tweaks) any existing connections will continue while all new traffic goes to the new process.

I will be submitting a pull request in the next couple of days when I get a chance to write some tests for it.

**Comment by surajwy** [comment] 2016-05-22 09:56
Hey All, 
I also tried writing a hello world program using Express.js and tried firing an ab benchmark over it. However, for me it all worked good with zero errors.
Here are my scripts:

web.js
```
var express = require('express');
var app = express();

app.get('/', function (req, res) {
    console.log(process.pid);
  res.status(200).send('Hello World! ');
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

The ab command that I used:
```
ab -c 1000 -n 100000 http://localhost:3000/
```

Here is the reload command
``` 
watch "pm2 reload all" 
```

Here is the ab output
```
Concurrency Level:      1000
Time taken for tests:   69.948 seconds
Complete requests:      100000
Failed requests:        0
Write errors:           0
Total transferred:      20700000 bytes
HTML transferred:       1300000 bytes
Requests per second:    1429.63 [#/sec] (mean)
Time per request:       699.481 [ms] (mean)
Time per request:       0.699 [ms] (mean, across all concurrent requests)
Transfer rate:          289.00 [Kbytes/sec] received
```

**Comment by mirkods** [comment] 2016-05-23 07:10
@surajwy thanks for the response. 
A hello world app I think is not the best case to test it. 
As I wrote on my first post when my server starts it needs a setup time ( like for example db connection, redis connection and so on) before it's ready so I think that in this time window I lose the connections that the benchmark says

**Comment by jamiemcconnell** [comment] 2016-05-23 07:16
I'll write a quick test app which demonstrates the issue - any new connections should _not_ be served by the old process id; I had a fix for this but as gracefulReload is being depricated i need to tweak it a bit.

**Comment by mirkods** [comment] 2016-06-06 07:38
any news about?

**Comment by mirkods** [comment] 2016-06-06 13:58
Hey @jamiemcconnell,
I'm trying to send the `process.send('online')` command in the callback of the `createServer` function but seems that it is ignore from pm2 because pm2 continues to print `App name:----- id:58 online` before the server is running.

Any suggestions?

**Comment by godspeedelbow** [comment] 2016-07-01 08:47
Any ideas how to fix this? I'm running into the exact same problem. Having more instances seems to cause more downtime, not less

**Comment by vmarchaud** [comment] 2016-09-23 19:52
Duplicate as #2353
PR #2401 is on the way to dev branch.

**Closed by vmarchaud** 2016-09-23 19:52 UTC

**Comment by godspeedelbow** [comment] 2016-09-26 07:00
awesome-o!
