### ISSUE TITLE
Node 0.12 - PM2@latest and cluster_mode passing to all processes

### ISSUE THREAD

**Issue by askhogan** [Unitech/PM2#1000] opened 2015-02-08 10:12 UTC
I setup a simple express script.  I then set it up similar to the existing examples and existing test cases

I setup a simple route that does nothing but log.  I performed an http GET to this route and I received log writing on all 8 processes.  Per the documentation it seemed that PM2 handles routing to only one cluster process at a time.  I am not seeing that happen.  All processes get the same GET request and perform the same call 8x times.  

How do you setup a config to only process 1 time per API request?

API-7 (out): 2015-02-08 10:10 +00:00: [2015-02-08 10:10:28.585] [WARN] api - healthy
API-6 (out): 2015-02-08 10:10 +00:00: [2015-02-08 10:10:28.585] [WARN] api - healthy
API-5 (out): 2015-02-08 10:10 +00:00: [2015-02-08 10:10:28.585] [WARN] api - healthy
API-4 (out): 2015-02-08 10:10 +00:00: [2015-02-08 10:10:28.585] [WARN] api - healthy
API-3 (out): 2015-02-08 10:10 +00:00: [2015-02-08 10:10:28.585] [WARN] api - healthy
API-2 (out): 2015-02-08 10:10 +00:00: [2015-02-08 10:10:28.585] [WARN] api - healthy
API-1 (out): 2015-02-08 10:10 +00:00: [2015-02-08 10:10:28.585] [WARN] api - healthy
API-0 (out): 2015-02-08 10:10 +00:00: [2015-02-08 10:10:28.585] [WARN] api - healthy

**Comment by thomaschaaf** [comment] 2015-02-12 23:19
I am seeing this too, which sort of defeats the purpose.

**Comment by askhogan** [comment] 2015-02-13 00:36
Totally.  Seems like a super solid program.  The clustering makes a lot of sense to me, because Elastic Load Balancer can only connect to one port.  So it seems intuitive to have ELB -> PM2 Cluster Port -> PM2 Workers to gain 100% uptime.  Only issue is as soon as there are multiple 

What I cannot wrap my head around is how PM2 takes a port (e.g. 3000) which is bound to a system resource.  Is it somehow modifying express on the fly to change the port.  What I was expecting was there would be one main PM2 port that would then proxy connections to another port.  So my ELB would only point to that one port.  Instead what it seems is there is some magic behind the scenes to do this for you.  It just makes me suspicious, because NAT, port or network card virtualization seems like an extremely complicated task.  

From the docs it just says

With the cluster mode, PM2 enables load balancing between each worker. Each HTTP/TCP/UDP request will be forwarded to one specific process at a time.

But how does it do this?  Where in the code?

**Comment by soyuka** [comment] 2015-02-13 07:39
Hi @askhogan, pm2 is using the [`cluster`](nodejs.org/api/cluster.html) module ([code](https://github.com/joyent/node/blob/master/lib/cluster.js)), there is no port modification anywhere. 
Under the hood, it's simply forking an app and redirecting your request to the first worker available. I remind you that it's the clustering module that does this, not pm2 itself.

Here in pm2, God is the [cluster master](https://github.com/Unitech/PM2/blob/master/lib/God.js#L27), the forking is done [here](https://github.com/Unitech/PM2/blob/master/lib/God/ClusterMode.js#L50). You might also want to take a look at [ProcessContainer](https://github.com/Unitech/PM2/blob/master/lib/ProcessContainer.js), this is where your process is living.

**Comment by bwin** [comment] 2015-02-15 01:58
@askhogan it does work exactly as you expected. You can verify that with the following:
```javascript
// app.js
var http = require('http');
http.createServer(function(req, res) {
	console.log("req", req.method, req.url);
	res.writeHead(200);
	res.end('hey '+ (new Date()));
}).listen(8000);
```

Then start it with `pm2 start --name testapp -i 4 app.js`. Watch the logs with `pm2 logs` and make a request to localhost:8000. You will see that only one worker responds (everything else wouldn't make sense).
As soyuka pointed out this is done with the cluster module from node-core. Only node > 0.10 is suppored though.
Have you checked your node version? If you're using a supported node version, you should investigate why your app won't work with the cluster module, since an express app out of the box should work AFAIK.

**Comment by bwin** [comment] 2015-02-15 02:29
I can confirm that it does (at least for me) work with express (latest) out of the box.
```javascript
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  console.log("req", req.method, req.url);
  res.send('hey from pm2 worker #' + process.env.pm_id + '\n' + new Date());
});

var server = app.listen(3000, function () {
  var host = server.address().address;
  var port = server.address().port;
  console.log('Example app listening at http://%s:%s', host, port);
});
```

**Comment by askhogan** [comment] 2015-02-15 05:36
thanks for posting express example.  that was going to be my response to the first comment.  I was using express and node .12.  I must have something in my setup that is causing this.  I am going to check in the morning to see what is going on with my app or logger, log4js.

**Comment by thomaschaaf** [comment] 2015-02-15 10:39
I found the problem!
It is related to the ```--log``` flag. Setting it results ```pm2 logs``` outputting everything for every instance.

test.js:
```
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  console.log("req", req.method, req.url);
  res.send('hey from pm2 worker #' + process.env.pm_id + '\n' + new Date());
});

var server = app.listen(3000, function () {
  var host = server.address().address;
  var port = server.address().port;
  console.log('Example app listening at http://%s:%s', host, port);
});
```

```
pm2 start -i 4 test.js
pm2 logs
HTTP response -> hey from pm2 worker #33 Sun Feb 15 2015 10:38:43 GMT+0000 (UTC)
Log:
test-33 (out): req GET /
```

```
pm2 start -i 4 -l test.out test.js
pm2 logs
HTTP response -> hey from pm2 worker #29 Sun Feb 15 2015 10:37:44 GMT+0000 (UTC)
Log: 
test-31 (entire): req GET /
test-29 (entire): req GET /
test-32 (entire): req GET /
test-30 (entire): req GET /
```

**Comment by Tjatse** [comment] 2015-02-15 11:13
@thomaschaaf `--log` is designed to debug error context. of course the logs exist every where (could be duplicated in separated logs).
@askhogan 's example seems irrelevant to the `entire` log, it's `out`.

**Comment by bwin** [comment] 2015-02-15 13:51
@thomaschaaf `-l` merges error and out logs into a single file, but you still have separate logfiles for each instance. (Check with `pm2 info APPNAME`.)

`pm2 logs APPNAME` (or just `pm2 logs`) displays the logs of all instances. To view the log of a single instance you would do `pm2 logs ID`.

From `pm2 --help`:
> `logs [options] [id|name]                                   stream logs file. Default stream all logs`

**Comment by askhogan** [comment] 2015-02-15 20:21
@bwin you indicate you are using pm2 0.12.5

But according to releases 0.12.4 is the latest?

**Comment by bwin** [comment] 2015-02-15 20:32
I've got lthe latest stable from npm. That's 0.12.5. See https://www.npmjs.com/package/pm2

**Comment by askhogan** [comment] 2015-02-15 20:34
Ok weird.  They must be out of sync on GH releases.  I will install that version.  

Thank you for your example yesterday showing the worker ID.  This just helped me isolate.  Here is my log output.  It seems I am getting log output from the same worker.  digging deeper.  This may just be a logging issue or conflict with my logging app log4js

testapp-7 (out): 2015-02-15 20:31 +00:00: [2015-02-15 20:31:56.932] [WARN] app - hey from pm2 worker #3
testapp-7 (out): Sun Feb 15 2015 20:31:56 GMT+0000 (GMT)
testapp-2 (out): 2015-02-15 20:31 +00:00: [2015-02-15 20:31:56.932] [WARN] app - hey from pm2 worker #3
testapp-2 (out): Sun Feb 15 2015 20:31:56 GMT+0000 (GMT)
testapp-6 (out): 2015-02-15 20:31 +00:00: [2015-02-15 20:31:56.932] [WARN] app - hey from pm2 worker #3
testapp-6 (out): Sun Feb 15 2015 20:31:56 GMT+0000 (GMT)
testapp-1 (out): 2015-02-15 20:31 +00:00: [2015-02-15 20:31:56.932] [WARN] app - hey from pm2 worker #3
testapp-1 (out): Sun Feb 15 2015 20:31:56 GMT+0000 (GMT)
testapp-0 (out): 2015-02-15 20:31 +00:00: [2015-02-15 20:31:56.932] [WARN] app - hey from pm2 worker #3
testapp-0 (out): Sun Feb 15 2015 20:31:56 GMT+0000 (GMT)
testapp-5 (out): 2015-02-15 20:31 +00:00: [2015-02-15 20:31:56.932] [WARN] app - hey from pm2 worker #3
testapp-5 (out): Sun Feb 15 2015 20:31:56 GMT+0000 (GMT)
testapp-4 (out): 2015-02-15 20:31 +00:00: [2015-02-15 20:31:56.932] [WARN] app - hey from pm2 worker #3
testapp-4 (out): Sun Feb 15 2015 20:31:56 GMT+0000 (GMT)
testapp-3 (out): 2015-02-15 20:31 +00:00: [2015-02-15 20:31:56.932] [WARN] app - hey from pm2 worker #3
testapp-3 (out): Sun Feb 15 2015 20:31:56 GMT+0000 (GMT)

**Comment by thomaschaaf** [comment] 2015-02-15 20:36
@askhogan have you tried not using any of the logging flags? Or if you are using the json then removing them? That has helped for me.

```
    -l --log [path]                      specify entire log file (error and out are both included)
    -o --output <path>                   specify out log file
    -e --error <path>                    specify error log file
```

**Comment by askhogan** [comment] 2015-02-15 20:43
@thomaschaaf Thanks for point that out in your earlier comments.  That lead me to figuring out the issue for my config.  I change merge_logs from true to false and now I am getting just one log entry.  This is the new config I am using

```
{
  "apps" : [{
    "exec_interpreter"   : "node",
    "exec_mode"          : "cluster_mode",
    "instances"          : 0,
    "log_date_format"    : "YYYY-MM-DD HH:mm Z",
    "merge_logs"         : false,
    "name"               : "testapp",
    "script"             : "dashboard.js",
    "cwd"                : "_dashboard/server",
    "node_args"          : "--harmony",
    "ignoreWatch"        : ["[\\/\\\\]\\./", "log"],
    "watch"              : false
  }]
}
```

**Comment by askhogan** [comment] 2015-02-15 20:53
I was able to recreate this using @bwin 's example 

process.json
```
{
  "apps" : [{
    "exec_interpreter"   : "node",
    "exec_mode"          : "cluster_mode",
    "instances"          : 0,
    "log_date_format"    : "YYYY-MM-DD HH:mm Z",
    "max_memory_restart" : "160",
    "merge_logs"         : true,
    "name"               : "testapp",
    "script"             : "server.js",
    "cwd"                : "dashboard",
    "node_args"          : "--harmony",
    "ignoreWatch"        : ["[\\/\\\\]\\./", "log"],
    "watch"              : true
  }]
}

dashboard/server.js
```
var express = require('express');
var app = express();

app.get('/', function (req, res) {
    console.log("req", req.method, req.url);
    res.send('hey from pm2 worker #' + process.env.pm_id + '\n' + new Date());
});

var server = app.listen(3045, function () {
    var host = server.address().address;
    var port = server.address().port;
    console.log('Example app listening at http://%s:%s', host, port);
});
```
node 0.12 pm2 0.12.5

Run the command *pm2 start process.json* 

Run the command *pm2 logs* 

Then run a GET command to http://localhost:3045/

**Comment by jshkurti** [comment] 2015-02-16 16:09
```What I cannot wrap my head around is how PM2 takes a port (e.g. 3000) which is bound to a system resource and defined in each file that then gets clustered to 8 separate processes (which would inherently cause a port conflict).```

As said earlier in this post, PM2 uses Node.js' cluster module.
There is no port conflict because cluster module internally spawns workers which listen on different ports (e.g if your app listens to port 3000 and you have 4 workers they probably will be listening on 3001, 3002, 3003 and 3004).
The master keeps listening on the port you chose though and then redirects the requests to the most avaible worker.

I'm closing this issue since it's a log problem and not a cluster_module one :)

**Comment by askhogan** [comment] 2015-02-16 16:12
@jshkurti  :) There was a confirmed bug in here though.  I will re-open under another banner

**Comment by thomaschaaf** [comment] 2015-02-16 16:12
Not entierly sure this should be closed...

**Comment by askhogan** [comment] 2015-02-16 16:15
I get his point.  Its the title and beginning, he doesnt want to confuse ppl.  I opened a new ticket here for the confirmed logging issue --> https://github.com/Unitech/PM2/issues/1021

**Comment by jshkurti** [comment] 2015-02-16 16:15
Thanks :)

**Comment by bwin** [comment] 2015-02-16 16:16
Then please give a lightweight example to reproduce your error.

**Closed by jshkurti** 2015-02-16 16:15 UTC
Labels: need investigation

**Comment by askhogan** [comment] 2015-02-16 16:30
@bwin read above and check ticket.  I used your example.

**Comment by mogongzi** [comment] 2016-05-05 09:22
Hi @askhogan,

Do you use log4js module under pm2 cluster mode successfully? Could you please refer the following issue?
https://github.com/Unitech/pm2/issues/383
